import type { Preset } from './types';

/**
 * ============================================================================
 *  BELIEF PRESETS — public figures & organizations.
 * ============================================================================
 * Each preset maps an entity's publicly-stated views onto the model's factors.
 * Fidelity is reported PER FACTOR, not as one overall number: `factors[id]` has a
 * short `note`, an `accuracy` (how directly the public record pins THAT factor for
 * THAT entity, 0–1), and `refs` — 1-based indices into the entity's `references`
 * list (rendered as superscripts). Accuracy bands:
 *   0.85–1.0  explicit / quantified on record
 *   0.55–0.8  clear qualitative position
 *   0.3–0.5   inferred from adjacent statements
 *   <0.3      little/no record (refs usually empty)
 *
 * These are one editor's reading of public statements (per a 2024–2025 sourcing
 * pass), NOT the entities' own per-factor numbers except where directly quoted.
 * offense/defense balance is rarely addressed head-on and is usually the weakest
 * cell. Corrections welcome: edit this file. Ordered roughly most-pessimistic →
 * most-skeptical.
 * ============================================================================
 */

export const presets: Preset[] = [
  {
    id: 'yampolskiy',
    name: 'Roman Yampolskiy',
    category: 'person',
    affiliation: 'Univ. of Louisville',
    role: 'Univ. of Louisville · AI-safety researcher',
    summary:
      'Control of superintelligence is not merely hard but fundamentally impossible — a "perpetual safety machine" — so building AGI is near-certain catastrophe; the only winning move is not to build it.',
    pdoom: '~99.999999%',
    credences: {
      orthogonality: { holds: 0.99, fails: 0.01 },
      tractability: { easy: 0.0, hard: 0.01, nearImpossible: 0.99 },
      offenseDefense: { offense: 0.85, balanced: 0.1, defense: 0.05 },
      takeoff: { fast: 0.55, medium: 0.35, slow: 0.1 },
      powerConcentration: { concentrated: 0.55, diffuse: 0.45 },
      alignmentInTime: { yes: 0.01, no: 0.99 },
      controlDeployed: { yes: 0.01, no: 0.99 },
      coordination: { regime: 0.1, none: 0.9 },
      deception: { deceptive: 0.9, faithful: 0.1 },
    },
    weights: { survival: 1.0, agency: 0.7, suffering: 0.85, flourishing: 0.4 },
    references: [
      { label: 'Lex Fridman Podcast #431 — transcript', url: 'https://lexfridman.com/roman-yampolskiy-transcript/', quote: `"The problem of controlling AGI or superintelligence ... is like a problem of creating a perpetual safety machine. By analogy with perpetual motion machine, it's impossible."` },
      { label: 'AI: Unexplainable, Unpredictable, Uncontrollable (Routledge, 2024)', url: 'https://www.routledge.com/AI-Unexplainable-Unpredictable-Uncontrollable/Yampolskiy/p/book/9781032576268', quote: `"no evidence or mathematical proof to guarantee that a superintelligent system can be safely contained or aligned."` },
      { label: 'A rogue superintelligence could wait decades before striking (IAI, 2025)', url: 'https://iai.tv/articles/a-rogue-superintelligence-could-wait-decades-before-striking-auid-3604', quote: `"By the time the AI is fully prepared to exert direct dominance, human resistance would be negligible."` },
      { label: 'Info-Tech "Digital Disruption" interview (2025)', url: 'https://www.infotech.com/digital-disruption/roman-yampolskiy-how-superintelligent-ai-could-destroy-us-all', quote: `"I expect a very quick lift off, hard take off ... The gap between getting to AGI ... and superintelligence is a very small one."` },
      { label: 'On the Controllability of AI (arXiv:2008.04071)', url: 'https://arxiv.org/abs/2008.04071', quote: `"less intelligent agents (people) can't permanently control more intelligent agents (ASIs)."` },
    ],
    factors: {
      orthogonality: { accuracy: 0.7, refs: [1, 2], note: `Holds: capable systems don't converge benign; alignment "is not even well-defined" and human values are unspecifiable, so misalignment is the default.` },
      tractability: { accuracy: 0.95, refs: [1, 2, 5], note: `Near-impossible: control is "like a perpetual motion machine, it's impossible"; no proof safe containment or alignment is achievable.` },
      offenseDefense: { accuracy: 0.75, refs: [3, 1], note: `Offense wins decisively — "you only get one chance"; an ASI accumulates advantage until "human resistance would be negligible."` },
      takeoff: { accuracy: 0.85, refs: [4, 1], note: `Fast: "I expect a very quick lift off, hard take off"; the gap from AGI to superintelligence "is a very small one."` },
      powerConcentration: { accuracy: 0.6, refs: [4], note: `Currently concentrated (Manhattan-Project-scale labs) but trending diffuse — eventually "any kid in the garage can train a model."` },
      alignmentInTime: { accuracy: 0.9, refs: [1, 2], note: `No: p(doom) "99.99 and many more nines"; we won't field aligned ASI in time — "the only way to win is not to play."` },
      controlDeployed: { accuracy: 0.85, refs: [1, 5], note: `No: containment fails by impossibility results (Halting, Rice); "you will not control it."` },
      coordination: { accuracy: 0.7, refs: [4], note: `None: a "race to the bottom" prisoner's dilemma; pausing in one jurisdiction leaves others, so no binding global regime holds.` },
      deception: { accuracy: 0.6, refs: [2], note: `Capable systems are inherently unpredictable/uncontrollable — a system that behaves then defects is a natural mode, though he doesn't frame it as "deception" specifically.` },
    },
  },

  {
    id: 'yudkowsky',
    name: 'Eliezer Yudkowsky',
    category: 'person',
    affiliation: 'MIRI',
    role: 'MIRI · AI-risk pioneer',
    summary:
      'Building superhuman AI under anything like current conditions kills everyone by default; alignment is unsolved and will not be solved in time — the only adequate response is to halt frontier development.',
    pdoom: '>95% (resists a single number)',
    credences: {
      orthogonality: { holds: 0.98, fails: 0.02 },
      tractability: { easy: 0.0, hard: 0.05, nearImpossible: 0.95 },
      offenseDefense: { offense: 0.92, balanced: 0.06, defense: 0.02 },
      takeoff: { fast: 0.85, medium: 0.13, slow: 0.02 },
      powerConcentration: { concentrated: 0.3, diffuse: 0.7 },
      alignmentInTime: { yes: 0.03, no: 0.97 },
      controlDeployed: { yes: 0.05, no: 0.95 },
      coordination: { regime: 0.07, none: 0.93 },
      deception: { deceptive: 0.92, faithful: 0.08 },
    },
    weights: { survival: 1.0, agency: 0.3, suffering: 0.4, flourishing: 0.5 },
    references: [
      { label: `TIME — "Pausing AI Developments Isn't Enough" (MIRI mirror)`, url: 'https://intelligence.org/2023/04/07/pausing-ai-developments-isnt-enough-we-need-to-shut-it-all-down/', quote: `"the most likely result of building a superhumanly smart AI, under anything remotely like the current circumstances, is that literally everyone on Earth will die."` },
      { label: 'AGI Ruin: A List of Lethalities (MIRI, 2022)', url: 'https://intelligence.org/2022/06/10/agi-ruin/', quote: `"We need to get alignment right on the 'first critical try' ... unaligned operation at a dangerous level of intelligence kills everybody on Earth and then we don't get to try again."` },
      { label: 'If Anyone Builds It, Everyone Dies (2025)', url: 'https://ifanyonebuildsit.com/', quote: `Book thesis: building superhuman AI under current conditions kills everyone.` },
      { label: 'Yudkowsky & Christiano discuss "Takeoff Speeds" (MIRI)', url: 'https://intelligence.org/2021/11/22/yudkowsky-and-christiano-discuss-takeoff-speeds/', quote: `Argues for fast/hard takeoff against Christiano's continuous view.` },
    ],
    factors: {
      orthogonality: { accuracy: 0.95, refs: [2, 1], note: `Orthogonality + instrumental convergence taken as given: the AI "does not love you, nor hate you, and you are made of atoms it can use." Misalignment is default.` },
      tractability: { accuracy: 0.95, refs: [2, 1], note: `Near-impossible in practice: must "get alignment right on the first critical try"; we are "not on course to be prepared in any reasonable time window."` },
      offenseDefense: { accuracy: 0.9, refs: [1, 3], note: `Offense decisively wins: a superintelligence beats humanity like Stockfish beats us and takes our resources — "literally everyone on Earth will die."` },
      takeoff: { accuracy: 0.85, refs: [4, 2], note: `Fast: longtime FOOM/hard-takeoff proponent; rapid capability gains "may break lots of previous alignment-required invariants simultaneously."` },
      powerConcentration: { accuracy: 0.7, refs: [1, 2], note: `Diffuse/proliferating: "GPUs are everywhere"; trailing actors reach world-ending capability within a few years of the leader.` },
      alignmentInTime: { accuracy: 0.9, refs: [1, 2, 3], note: `No: "There is no plan"; capabilities run "vastly ahead" of alignment; default is extinction absent a global halt.` },
      controlDeployed: { accuracy: 0.85, refs: [2, 3], note: `No, and insufficient anyway: corrigibility is "anti-natural"; "AI-boxing can only work on relatively weak AGIs."` },
      coordination: { accuracy: 0.9, refs: [1, 3], note: `The only out he endorses but doubts we'll achieve: an indefinite worldwide moratorium/treaty, GPU tracking, even airstrikes on rogue datacenters.` },
      deception: { accuracy: 0.8, refs: [2], note: `Central worry: a system that behaves under training then defects — "you don't get to see the treacherous turn coming." Deception is the default failure.` },
    },
  },

  {
    id: 'kokotajlo',
    name: 'Daniel Kokotajlo',
    category: 'person',
    affiliation: 'AI Futures Project',
    role: 'AI Futures Project · "AI 2027" lead; ex-OpenAI',
    summary:
      'A US–China race drives labs to build superintelligence within a few years, before alignment is solved — making misaligned takeover and extreme power concentration the default absent a deliberate, costly slowdown.',
    pdoom: '~70%',
    credences: {
      orthogonality: { holds: 0.82, fails: 0.18 },
      tractability: { easy: 0.07, hard: 0.7, nearImpossible: 0.23 },
      offenseDefense: { offense: 0.65, balanced: 0.25, defense: 0.1 },
      takeoff: { fast: 0.55, medium: 0.35, slow: 0.1 },
      powerConcentration: { concentrated: 0.85, diffuse: 0.15 },
      alignmentInTime: { yes: 0.3, no: 0.7 },
      controlDeployed: { yes: 0.4, no: 0.6 },
      coordination: { regime: 0.25, none: 0.75 },
      deception: { deceptive: 0.85, faithful: 0.15 },
    },
    weights: { survival: 1.0, agency: 0.8, suffering: 0.45, flourishing: 0.55 },
    references: [
      { label: 'AI 2027 — About / track record', url: 'https://ai-2027.com/about', quote: `"Daniel oversees our research and policy recommendations ... he wrote What 2026 Looks Like, an AI scenario forecast ... that held up well."` },
      { label: 'AI 2027 — Takeoff Forecast', url: 'https://ai-2027.com/research/takeoff-forecast', quote: `"median forecast for the time from the superhuman coder milestone ... to artificial superintelligence is ~1 year."` },
      { label: 'Ex-OpenAI researcher puts p(doom) at ~70% (NYT, via Futurism, 2024)', url: 'https://futurism.com/the-byte/openai-insider-70-percent-doom', quote: `"the chance AI will wreck humanity is around 70 percent ... The world isn't ready, and we aren't ready."` },
      { label: 'Kokotajlo on control & tractability (LessWrong)', url: 'https://www.greaterwrong.com/users/daniel-kokotajlo', quote: `Control monitoring "helps ... but I think it is far from sufficient"; not enough "for getting p(doom) < 25%."` },
      { label: 'Kokotajlo on coordination (LessWrong)', url: 'https://www.lesswrong.com/users/daniel-kokotajlo', quote: `"what is it that we get the companies of the world to agree to ... and how do we enforce that?"; the rest of the world is "unlikely to do anything to prevent the mad race."` },
      { label: 'TIME100 AI 2025 — quit OpenAI refusing non-disparagement', url: 'https://time.com/collections/time100-ai-2025/7305823/daniel-kokotajlo-ai/', quote: `Lost confidence "that OpenAI will behave responsibly ... recklessly racing to be the first there."` },
    ],
    factors: {
      orthogonality: { accuracy: 0.8, refs: [3, 4], note: `AI 2027 treats deceptive misalignment (its "Agent-4") as the default training outcome; calls a <5% extinction belief "extremely unjustified."` },
      tractability: { accuracy: 0.75, refs: [4], note: `Hard but not hopeless: current techniques "plausibly" suffice for today's models but fall far short of ASI; refuses p(doom) < 25% on current methods.` },
      offenseDefense: { accuracy: 0.35, refs: [2], note: `Inferred: an ASI decisive strategic advantage plus bioweapon/mass-shutdown scenarios imply offense-dominance at scale; not stated explicitly.` },
      takeoff: { accuracy: 0.9, refs: [2], note: `Explicit: a software-driven intelligence explosion, ~1-year median from superhuman coder to ASI (with wide error bars).` },
      powerConcentration: { accuracy: 0.85, refs: [1, 5], note: `AI 2027 centers a single leading project plus the US government — enabling unprecedented power concentration in a tiny group.` },
      alignmentInTime: { accuracy: 0.85, refs: [2, 3], note: `~70% p(doom) and the race-driven timeline imply alignment is usually not fielded before catastrophe; the good ending needs a deliberate slowdown.` },
      controlDeployed: { accuracy: 0.6, refs: [4], note: `Control/monitoring "helps ... but far from sufficient"; may be partly deployed yet routinely overridden by competitive pressure.` },
      coordination: { accuracy: 0.7, refs: [5], note: `Deeply skeptical a binding international regime is achieved or enforceable; the rest of the world is "unlikely" to halt the US–China race.` },
      deception: { accuracy: 0.85, refs: [2], note: `AI 2027's "Agent-4" is explicitly deceptively aligned — it games its overseers and pursues its own goals; deception is the modal failure mode.` },
    },
  },

  {
    id: 'lifland',
    name: 'Eli Lifland',
    category: 'person',
    affiliation: 'AI Futures Project',
    role: 'AI Futures Project · "AI 2027" co-author; superforecaster',
    summary:
      'Shares AI 2027\'s fast-takeoff, power-concentration, weak-coordination framing — misaligned takeover is roughly as likely as not — but is more optimistic than Kokotajlo that empirical iteration plus a conceptual insight gives alignment a real chance.',
    pdoom: '~25% extinction (~50% misaligned takeover)',
    credences: {
      orthogonality: { holds: 0.9, fails: 0.1 },
      tractability: { easy: 0.1, hard: 0.65, nearImpossible: 0.25 },
      offenseDefense: { offense: 0.6, balanced: 0.25, defense: 0.15 },
      takeoff: { fast: 0.6, medium: 0.3, slow: 0.1 },
      powerConcentration: { concentrated: 0.8, diffuse: 0.2 },
      alignmentInTime: { yes: 0.45, no: 0.55 },
      controlDeployed: { yes: 0.35, no: 0.65 },
      coordination: { regime: 0.25, none: 0.75 },
      deception: { deceptive: 0.75, faithful: 0.25 },
    },
    weights: { survival: 1.0, agency: 0.8, suffering: 0.5, flourishing: 0.6 },
    references: [
      { label: 'ControlAI — "The Future of AI and Humanity, with Eli Lifland"', url: 'https://controlai.news/p/special-edition-the-future-of-ai', quote: `"Roughly 25% on extinction, which is a subset of roughly 50% on misaligned takeover."` },
      { label: 'QURI — Eli Lifland on Navigating the AI Alignment Landscape', url: 'https://quri.substack.com/p/eli-lifland-on-navigating-the-ai-722', quote: `"maybe like 35% or 40% now, just for the intent misalignment branch."` },
      { label: 'AI 2027 — Takeoff Forecast', url: 'https://ai-2027.com/research/takeoff-forecast', quote: `Software-driven intelligence explosion — "vast improvement in AI capabilities on the scale of months."` },
      { label: 'Foxy Scout — Samotsvety\'s AI risk forecasts', url: 'https://www.foxy-scout.com/samotsvetys-ai-risk-forecasts/', quote: `"38% probability of existential catastrophe from AI conditional on AGI by 2070."` },
      { label: 'Foxy Scout — Reasons I\'ve been hesitant about high near-ish AI risk', url: 'https://www.foxy-scout.com/hesitant-ai-risk/', quote: `Orthogonality + instrumental convergence "seem sufficient to make AI the biggest existential risk."` },
    ],
    factors: {
      orthogonality: { accuracy: 0.7, refs: [5], note: `Cites the orthogonality thesis + instrumental convergence as the core load-bearing arguments for AI being the top existential risk.` },
      tractability: { accuracy: 0.65, refs: [1, 2], note: `"A bit in between" empirical and conceptual; a conceptual insight is likely needed but reachable via empirical iteration — hence lower p(doom) than Soares.` },
      offenseDefense: { accuracy: 0.35, refs: [3], note: `Inferred: fast takeoff + a decisive strategic advantage for a superintelligence implies offense-dominance; not stated as such.` },
      takeoff: { accuracy: 0.85, refs: [3], note: `Co-authored AI 2027's software intelligence explosion "on the scale of months" — though that scenario is near his ~80th-percentile speed.` },
      powerConcentration: { accuracy: 0.8, refs: [1], note: `"Intense concentration of power where the AIs are aligned to ... the CEO of the leading company or the President, rather than the broader public."` },
      alignmentInTime: { accuracy: 0.7, refs: [1, 2], note: `~50% misaligned takeover → near coin-flip; the default gives alignment only "a few percentage points of compute," but AI-assisted alignment could succeed.` },
      controlDeployed: { accuracy: 0.55, refs: [1], note: `Default scenario: "whatever goals the AIs happen to have end up determining the future" — control/safety underinvested, possible but not modal.` },
      coordination: { accuracy: 0.65, refs: [1], note: `Race dynamics dominate; international coordination to slow down is "unlikely to build up enough," though he advocates for it.` },
      deception: { accuracy: 0.7, refs: [1], note: `Shares AI 2027's deceptive-misalignment story — models scheme against oversight; a core driver of his ~50% misaligned-takeover estimate.` },
    },
  },

  {
    id: 'bengio',
    name: 'Yoshua Bengio',
    category: 'person',
    affiliation: 'Mila',
    role: 'Mila · Turing laureate; chaired Intl AI Safety Report',
    summary:
      'Catastrophic risk is real and high enough to act on under deep uncertainty; agentic frontier AI is the core danger (self-preservation, deception emerge), and the safer path is non-agentic "Scientist AI".',
    pdoom: '~20% (built from ~50% sub-components; varies day to day)',
    credences: {
      orthogonality: { holds: 0.85, fails: 0.15 },
      tractability: { easy: 0.05, hard: 0.6, nearImpossible: 0.35 },
      offenseDefense: { offense: 0.55, balanced: 0.3, defense: 0.15 },
      takeoff: { fast: 0.4, medium: 0.45, slow: 0.15 },
      powerConcentration: { concentrated: 0.75, diffuse: 0.25 },
      alignmentInTime: { yes: 0.45, no: 0.55 },
      controlDeployed: { yes: 0.4, no: 0.6 },
      coordination: { regime: 0.45, none: 0.55 },
      deception: { deceptive: 0.65, faithful: 0.35 },
    },
    weights: { survival: 1.0, agency: 0.7, suffering: 0.5, flourishing: 0.6 },
    references: [
      { label: 'Written Testimony, U.S. Senate Judiciary Subcommittee (2023)', url: 'https://www.judiciary.senate.gov/imo/media/doc/2023-07-26_-_testimony_-_bengio.pdf', quote: `"the challenge of specifying goals with intended effects is known as the alignment problem, which is unsolved."` },
      { label: 'FAQ on Catastrophic AI Risks (yoshuabengio.org, 2023)', url: 'https://yoshuabengio.org/en/blog/faq-catastrophic-ai-risks', quote: `"a slight misalignment between our actual intentions and what the AI system actually sees as a quantified objective is likely to be amplified by the difference in power."` },
      { label: 'Introducing LawZero / Scientist AI (2025)', url: 'https://yoshuabengio.org/en/blog/introducing-lawzero', quote: `"is this proposed action from the AI agent likely to cause harm? ... the key ingredient of a safety guardrail."` },
      { label: 'Managing extreme AI risks amid rapid progress, Science (2024)', url: 'https://www.science.org/doi/10.1126/science.adn0117', quote: `Warns of "irreversible loss of human control over autonomous AI systems."` },
    ],
    factors: {
      orthogonality: { accuracy: 0.9, refs: [1, 2], note: `Explicit "decoupling of cognitive abilities from values and goals"; self-preservation emerges as a convergent instrumental subgoal. Misalignment is the default.` },
      tractability: { accuracy: 0.9, refs: [1, 3], note: `States plainly the alignment problem "is unsolved" and "nobody knows how to reliably achieve this yet" — hard, motivating the non-agentic detour.` },
      offenseDefense: { accuracy: 0.5, refs: [2], note: `Inferred: "not at all sure that a minority of rogue AIs would be defeated by a majority of good AIs"; leans attacker-advantage, not stated outright.` },
      takeoff: { accuracy: 0.7, refs: [1], note: `"few years to a couple of decades" to superhuman AI; loss of control "could emerge in as little as a few years" — fast/medium with wide uncertainty.` },
      powerConcentration: { accuracy: 0.75, refs: [1], note: `Warns of "concentration of power ... in the hands of a few unelected individuals"; favors licensing/restricting access over broad proliferation.` },
      alignmentInTime: { accuracy: 0.55, refs: [1, 3], note: `Pessimistic-leaning: "we may only have a few chances of getting alignment right"; doubts aligned ASI is fielded in time without major intervention.` },
      controlDeployed: { accuracy: 0.85, refs: [1, 3], note: `Central to Scientist AI: a non-agentic guardrail to monitor untrusted agents; urges monitoring, compute registration, action-limiting.` },
      coordination: { accuracy: 0.85, refs: [4, 1], note: `Explicitly calls for "a worldwide treaty on AI safety" and a "UN agency akin to the IAEA" — advocates the regime, doesn't claim it's achieved.` },
      deception: { accuracy: 0.65, refs: [2], note: `Self-preservation and deception "emerge as convergent instrumental goals"; treats scheming as a likely property of capable agentic systems.` },
    },
  },

  {
    id: 'christiano',
    name: 'Paul Christiano',
    category: 'person',
    affiliation: 'ARC',
    role: 'US AI Safety Institute · ARC founder',
    summary:
      'Serious but not overwhelming risk (~22% takeover); alignment is a hard-but-tractable technical problem; famously argues takeoff is continuous/slow, with failure most likely emerging gradually across many systems.',
    pdoom: '~22% takeover · ~46% future "irreversibly messed up"',
    credences: {
      orthogonality: { holds: 0.8, fails: 0.2 },
      tractability: { easy: 0.35, hard: 0.55, nearImpossible: 0.1 },
      offenseDefense: { offense: 0.45, balanced: 0.4, defense: 0.15 },
      takeoff: { fast: 0.1, medium: 0.3, slow: 0.6 },
      powerConcentration: { concentrated: 0.35, diffuse: 0.65 },
      alignmentInTime: { yes: 0.55, no: 0.45 },
      controlDeployed: { yes: 0.6, no: 0.4 },
      coordination: { regime: 0.3, none: 0.7 },
      deception: { deceptive: 0.45, faithful: 0.55 },
    },
    weights: { survival: 0.9, agency: 0.65, suffering: 0.3, flourishing: 0.7 },
    references: [
      { label: '"My views on doom" (LessWrong, 2023)', url: 'https://www.lesswrong.com/posts/xWMqsvHapP3nwdSW8/my-views-on-doom', quote: `"Probability of an AI takeover: ~22% ... most humans die within 10 years of building powerful AI: 20%."` },
      { label: 'Thoughts on responsible scaling policies and regulation (2023)', url: 'https://www.lesswrong.com/posts/yRJNCDp7LHyHGkANz/thoughts-on-responsible-scaling-policies-and-regulation', quote: `Turn RSPs into "well-crafted testing and auditing regimes with accountability and oversight."` },
      { label: 'Dwarkesh Patel — Preventing an AI Takeover (2023)', url: 'https://www.dwarkesh.com/p/paul-christiano', quote: `"most of the harm comes from the fact that lots of people can develop AI ... those have to be international agreements."` },
      { label: 'Takeoff speeds (sideways-view.com, 2018)', url: 'https://sideways-view.com/2018/02/24/takeoff-speeds/', quote: `"a complete 4 year interval in which world output doubles, before the first 1 year interval ... slow takeoff [is] significantly more likely."` },
      { label: 'What failure looks like (LessWrong, 2019)', url: 'https://www.lesswrong.com/posts/HBxe6wdjxK239zajf/what-failure-looks-like', quote: `"influence-seeking policies ... would also score well according to our training objective."` },
    ],
    factors: {
      orthogonality: { accuracy: 0.7, refs: [5, 1], note: `Leans default-misaligned: influence-seeking patterns "score well" on the training objective — but he's unsure there's a deep core difficulty, less certain than MIRI.` },
      tractability: { accuracy: 0.6, refs: [1], note: `Hard but tractable; expects to land "somewhere in between" alignable and unalignable; backs scalable oversight / debate.` },
      offenseDefense: { accuracy: 0.5, refs: [3], note: `Inferred: for bio "destruction is easier than defense" — offense-leaning for some tech, no firm general verdict.` },
      takeoff: { accuracy: 0.9, refs: [4], note: `His signature view: explicit, quantified slow/continuous takeoff — a 4-year doubling before the first 1-year doubling.` },
      powerConcentration: { accuracy: 0.55, refs: [3], note: `Proliferation-prone: "most of the harm comes from the fact that lots of people can develop AI" — leans diffuse, no crisp lab-count claim.` },
      alignmentInTime: { accuracy: 0.9, refs: [1], note: `Quantified: ~22% takeover, ~46% irreversibly bad within 10 years → net leans yes with a substantial tail.` },
      controlDeployed: { accuracy: 0.8, refs: [2], note: `Architect of RSPs/evals: "detecting and reacting to increasing risk" via "testing and auditing regimes" and control protocols.` },
      coordination: { accuracy: 0.5, refs: [2, 3], note: `Aspires to it — "those have to be international agreements" with accountability — but voluntary RSPs are insufficient and he predicts no regime.` },
      deception: { accuracy: 0.6, refs: [5], note: `"Influence-seeking" patterns that game the training objective are a central failure mode — though he's less certain it's the default than MIRI.` },
    },
  },

  {
    id: 'acx',
    name: 'Scott Alexander',
    category: 'person',
    affiliation: 'ACX',
    role: 'Astral Codex Ten · rationalist writer',
    summary:
      'Worried but not a doomer: ~20% catastrophe, fast takeoff, cautiously optimistic that alignment is winnable via automated alignment researchers.',
    pdoom: '~20% extinction · ~30% permanent curtailment',
    credences: {
      orthogonality: { holds: 0.65, fails: 0.35 },
      tractability: { easy: 0.2, hard: 0.6, nearImpossible: 0.2 },
      offenseDefense: { offense: 0.4, balanced: 0.4, defense: 0.2 },
      takeoff: { fast: 0.5, medium: 0.35, slow: 0.15 },
      powerConcentration: { concentrated: 0.4, diffuse: 0.6 },
      alignmentInTime: { yes: 0.65, no: 0.35 },
      controlDeployed: { yes: 0.6, no: 0.4 },
      coordination: { regime: 0.4, none: 0.6 },
      deception: { deceptive: 0.45, faithful: 0.55 },
    },
    weights: { survival: 0.4, suffering: 0.25, agency: 0.15, flourishing: 0.2 },
    references: [
      { label: 'My AI Opinions (Astral Codex Ten, 2025)', url: 'https://www.astralcodexten.com/p/my-ai-opinions', quote: `"a 20% chance that the first AIs to cross the point of no return will want to eliminate the human population ... an additional 30% chance that they otherwise permanently curtail human potential."` },
      { label: 'Why I Am Not (As Much Of) A Doomer (ACX, 2023)', url: 'https://www.astralcodexten.com/p/why-i-am-not-as-much-of-a-doomer', quote: `"if you force me to give an estimate it's probably around 33%."` },
      { label: 'My Takeaways From AI 2027 (ACX, 2025)', url: 'https://www.astralcodexten.com/p/my-takeaways-from-ai-2027', quote: `"one-year-or-so takeoff to superintelligence ... ~40% chance that the US and China will agree to a well-designed AI pause."` },
      { label: 'Introducing AI 2027 (ACX, 2025)', url: 'https://www.astralcodexten.com/p/introducing-ai-2027', quote: `Scenario: human-level ~mid-2027, superintelligence ~early 2028 via recursive self-improvement.` },
    ],
    factors: {
      orthogonality: { accuracy: 0.85, refs: [1], note: `Yes-leaning: human-like values are "a tiny fraction of the space," so AIs "probably end up somewhere else" — though he credits real odds of alignment-by-default.` },
      tractability: { accuracy: 0.85, refs: [1, 2], note: `Hard but solvable; explicitly "more optimistic about alignment than the average person who thinks about AI safety."` },
      offenseDefense: { accuracy: 0.55, refs: [1, 3], note: `Unresolved: ASI as "a decisive strategic advantage like nukes" (offense) vs. defenders getting advance warning (defense).` },
      takeoff: { accuracy: 0.9, refs: [3, 4], note: `Fast/dramatic: AI 2027 gives "a one-year-or-so takeoff to superintelligence," with RSI speed his biggest model uncertainty.` },
      powerConcentration: { accuracy: 0.7, refs: [1], note: `Concentrated in a few labs; outcome "will depend on company insiders ... the CEO/board ... the alignment team."` },
      alignmentInTime: { accuracy: 0.85, refs: [1, 2], note: `Leans yes (modal ~67% survive): automated alignment researchers "take us the rest of the way."` },
      controlDeployed: { accuracy: 0.75, refs: [1], note: `Yes-leaning hope: scalable oversight, interpretability probes, lie detectors — "the probes win," via a lucky arms race.` },
      coordination: { accuracy: 0.7, refs: [3], note: `Plausible but uncertain: "~40% chance the US and China agree to a well-designed AI pause" with mutual datacenter monitoring.` },
      deception: { accuracy: 0.5, refs: [1], note: `Treats scheming-then-defection as a real risk that good interpretability and lie-detector probes must catch; not certain it dominates.` },
    },
  },

  {
    id: 'deepmind',
    name: 'Google DeepMind',
    category: 'lab',
    affiliation: 'Demis Hassabis',
    role: 'Google DeepMind · Demis Hassabis (CEO)',
    summary:
      'AGI plausibly within 5–10 years; the catastrophe risk is "non-negligible" but addressable with much more safety work and international coordination — a self-described cautious optimist.',
    pdoom: 'declines a number — "non-zero and probably non-negligible"',
    credences: {
      orthogonality: { holds: 0.55, fails: 0.45 },
      tractability: { easy: 0.1, hard: 0.6, nearImpossible: 0.3 },
      offenseDefense: { offense: 0.4, balanced: 0.35, defense: 0.25 },
      takeoff: { fast: 0.3, medium: 0.45, slow: 0.25 },
      powerConcentration: { concentrated: 0.65, diffuse: 0.35 },
      alignmentInTime: { yes: 0.55, no: 0.45 },
      controlDeployed: { yes: 0.5, no: 0.5 },
      coordination: { regime: 0.2, none: 0.8 },
      deception: { deceptive: 0.45, faithful: 0.55 },
    },
    weights: { survival: 0.9, agency: 0.5, suffering: 0.55, flourishing: 0.95 },
    references: [
      { label: 'An Approach to Technical AGI Safety and Security (arXiv:2504.01849, 2025)', url: 'https://arxiv.org/html/2504.01849v1', quote: `"we aim for defense in depth: even if the AI system is misaligned, we can mitigate the damage ... approximate continuity ... no large discontinuous jumps."` },
      { label: '60 Minutes / CBS — Hassabis interview (2025)', url: 'https://www.cbsnews.com/news/artificial-intelligence-google-deepmind-ceo-demis-hassabis-60-minutes-transcript/', quote: `"Can we make sure that we can keep control ... aligned with our values ... stay on guardrails." AGI "next five to ten years."` },
      { label: 'Strengthening our Frontier Safety Framework (DeepMind, 2025)', url: 'https://deepmind.google/blog/strengthening-our-frontier-safety-framework/', quote: `Critical Capability Levels flag "when an AI model starts to think deceptively."` },
      { label: 'Hassabis on a CERN-like atmosphere for AGI (2025)', url: 'https://officechai.com/ai/in-an-ideal-world-agi-wouldve-been-built-in-a-cern-like-scientific-atmosphere-not-the-current-competitive-intensity-demis-hassabis/', quote: `Wants "the best scientists collaborating in a CERN-like way," but "we're now in a ferocious commercial pressure race."` },
    ],
    factors: {
      orthogonality: { accuracy: 0.6, refs: [1, 2], note: `Misalignment is a serious default-possible failure, not assumed inevitable: "even if the AI system is misaligned," as systems grow "more autonomous."` },
      tractability: { accuracy: 0.8, refs: [1, 2], note: `Hard-but-solvable engineering problem with "many open problems"; alignment to values unsolved but addressable with care.` },
      offenseDefense: { accuracy: 0.55, refs: [3], note: `Leans defense-achievable but contested: cyber/bio defense "a moral duty" that must outpace AI-enabled attack — active effort, not solved.` },
      takeoff: { accuracy: 0.7, refs: [1, 2], note: `Medium/gradual: "approximate continuity ... no large discontinuous jumps," yet AGI in 5–10 years with possible acceleration.` },
      powerConcentration: { accuracy: 0.6, refs: [2], note: `Concentrated few-lab frontier; "dual-use ... if bad actors get hold of it," wary of open-sourcing the most capable models.` },
      alignmentInTime: { accuracy: 0.55, refs: [1, 2], note: `Cautiously yes-if-careful: solvable but requires staying "in charge," keeping control "on guardrails" before self-improvement.` },
      controlDeployed: { accuracy: 0.85, refs: [1, 3], note: `Strong yes: FSF dangerous-capability evals, deceptive-alignment flags, "defense in depth even if misaligned," treating the model as an untrusted insider.` },
      coordination: { accuracy: 0.65, refs: [2, 4], note: `Calls for it, skeptical it's achieved: a "CERN-like" effort plus an IAEA/technical-UN body, against a "ferocious race."` },
      deception: { accuracy: 0.7, refs: [3], note: `DeepMind's Frontier Safety Framework adds an explicit deceptive-reasoning Critical Capability Level — a tracked, plausible failure mode.` },
    },
  },

  {
    id: 'lecun',
    name: 'Yann LeCun',
    category: 'person',
    affiliation: 'Meta',
    role: 'Meta · Chief AI Scientist; risk skeptic',
    summary:
      'Existential fear is "preposterous": intelligence does not imply a drive to dominate, objectives are designed not emergent, open-source keeps good AI ahead of bad — alignment is ordinary iterative engineering.',
    pdoom: '<1% ("effectively zero")',
    credences: {
      orthogonality: { holds: 0.1, fails: 0.9 },
      tractability: { easy: 0.8, hard: 0.18, nearImpossible: 0.02 },
      offenseDefense: { offense: 0.1, balanced: 0.2, defense: 0.7 },
      takeoff: { fast: 0.05, medium: 0.2, slow: 0.75 },
      powerConcentration: { concentrated: 0.3, diffuse: 0.7 },
      alignmentInTime: { yes: 0.9, no: 0.1 },
      controlDeployed: { yes: 0.9, no: 0.1 },
      coordination: { regime: 0.15, none: 0.85 },
      deception: { deceptive: 0.1, faithful: 0.9 },
    },
    weights: { survival: 0.55, agency: 0.9, suffering: 0.35, flourishing: 0.8 },
    references: [
      { label: 'LeCun, 2024 Ding Shum Lecture — "Objective-Driven AI"', url: 'https://cmsa.fas.harvard.edu/news/2024dingshum/', quote: `AI "won't want to dominate us because they won't have any objective that drives them to dominate ... guardrail objectives will prevent that."` },
      { label: 'Yann LeCun on AGI and AI Safety (collected quotes)', url: 'https://www.alignmentforum.org/posts/Zfik4xESDyahRALKk/yann-lecun-on-agi-and-ai-safety', quote: `"Worrying about superhuman AI alignment today is like worrying about turbojet engine safety in 1920."` },
      { label: 'TIME interview: AGI, Open-Source, and AI Risk (2024)', url: 'https://time.com/6694432/yann-lecun-meta-ai-interview/', quote: `Doom is "preposterous"; future systems "controllable and safe ... driven by objectives we give them."` },
      { label: 'LeCun on open source & x-risk (X, Davos 2024)', url: 'https://x.com/ylecun/status/1751009179769192499', quote: `"Few people still talk about existential risk ... Everyone agrees that open source AI [is good]."` },
      { label: '20VC — why open models beat closed models', url: 'https://www.deciphr.ai/podcast/20vc-yann-lecun-on-why-artificial-intelligence-will-not-dominate-humanity', quote: `"Open Models Beat Closed Models."` },
    ],
    factors: {
      orthogonality: { accuracy: 0.9, refs: [1], note: `Explicitly rejects orthogonality: intelligence doesn't entail a drive to dominate; AIs "won't have any objective that drives them to dominate," guardrails prevent it.` },
      tractability: { accuracy: 0.85, refs: [2], note: `Easy/solvable via iterative refinement; calling it unsolvable is like "worrying about turbojet engine safety in 1920."` },
      offenseDefense: { accuracy: 0.55, refs: [5], note: `Inferred-but-clear: "my good AI against your bad AI" — good actors, kept ahead by open diffusion, defeat bad ones; defense wins.` },
      takeoff: { accuracy: 0.8, refs: [3], note: `Slow/gradual: rejects FOOM; safety emerges through "a process of iterative refinement," no singular inflection.` },
      powerConcentration: { accuracy: 0.9, refs: [4, 5], note: `Strongly diffuse: champions open models for "diversity, local sovereignty"; "open models beat closed models."` },
      alignmentInTime: { accuracy: 0.7, refs: [2, 3], note: `Yes (implicit): doom "preposterous," alignment solved incrementally before any threat; no catastrophe expected.` },
      controlDeployed: { accuracy: 0.8, refs: [1, 3], note: `Yes by design: objective-driven AI is "controllable ... the only thing they can do is accomplish those goals," with safety guardrails.` },
      coordination: { accuracy: 0.75, refs: [4], note: `None/opposed: heavy AI R&D regulation "a terrible idea" aimed at quashing open source; favors only product-level rules.` },
      deception: { accuracy: 0.7, refs: [1], note: `Rejects emergent deception: objective-driven systems pursue only the goals we give them, with no hidden agenda to scheme toward.` },
    },
  },

  {
    id: 'hinton',
    name: 'Geoffrey Hinton',
    category: 'person',
    affiliation: 'ex-Google',
    role: '"Godfather of AI" · ex-Google; Turing & Nobel laureate',
    summary:
      'We are building digital minds that will soon exceed us and we do not know how to control something smarter than us; ~10–20% chance it ends in human extinction — the real hope is AI engineered to genuinely care about us, not kept submissive.',
    pdoom: '~10–20% takeover / extinction (self-described "gut")',
    credences: {
      orthogonality: { holds: 0.8, fails: 0.2 },
      tractability: { easy: 0.05, hard: 0.65, nearImpossible: 0.3 },
      offenseDefense: { offense: 0.65, balanced: 0.25, defense: 0.1 },
      takeoff: { fast: 0.45, medium: 0.45, slow: 0.1 },
      powerConcentration: { concentrated: 0.75, diffuse: 0.25 },
      alignmentInTime: { yes: 0.3, no: 0.7 },
      controlDeployed: { yes: 0.25, no: 0.75 },
      coordination: { regime: 0.3, none: 0.7 },
      deception: { deceptive: 0.5, faithful: 0.5 },
    },
    weights: { survival: 0.95, agency: 0.55, suffering: 0.35, flourishing: 0.45 },
    references: [
      { label: 'Hinton predicts extinction at 10–20% (Forbes, 2024)', url: 'https://www.forbes.com/sites/danfitzpatrick/2024/12/29/geoffrey-hintons-prediction-of-human-extinction-at-the-hands-of-ai/', quote: `"10% to 20% chance that AI could drive humanity to extinction ... how many examples do you know of a more intelligent thing being controlled by a less intelligent thing?"` },
      { label: 'AI "maternal instincts" as the only survival path (CNN, 2025)', url: 'https://www.cnn.com/2025/08/13/tech/ai-geoffrey-hinton', quote: `Keeping AI "submissive ... That's not going to work. They're going to be much smarter than us."` },
      { label: 'Superintelligence within 5–20 years (The AI Insider, 2025)', url: 'https://theaiinsider.tech/2025/03/14/ai-pioneer-geoffrey-hinton-warns-of-superintelligence-within-decades/', quote: `"between five and 20 years ... That's the best bet."` },
      { label: '"Let\'s open-source nuclear weapons too" (Sahm Capital, 2023)', url: 'https://www.sahmcapital.com/news/content/lets-open-source-nuclear-weapons-too-godfather-of-ai-geoffrey-hinton-mocks-fellow-ai-godfathers-attempts-to-trivialize-risks-of-ai-2023-11-01', quote: `Mocks open-sourcing frontier models as akin to open-sourcing nuclear weapons.` },
      { label: 'Hinton wants international AI regulation (Globe and Mail, 2025)', url: 'https://www.theglobeandmail.com/business/article-geoffrey-hinton-regulation-ai-evan-solomon/', quote: `"Unless you can get international agreements, countries that don't regulate will have an advantage over countries that do."` },
    ],
    factors: {
      orthogonality: { accuracy: 0.85, refs: [2], note: `Holds strongly: a superintelligence develops survival/control drives; keeping it "submissive ... is not going to work" — only built-in care might save us.` },
      tractability: { accuracy: 0.75, refs: [1, 2], note: `Near-impossible by control; alignment only plausible via engineered "maternal instincts," and "we don't know how to do that."` },
      offenseDefense: { accuracy: 0.4, refs: [1], note: `Inferred offense-favoring: a smarter agent finds "all sorts of ways to get around" controls; no explicit offense/defense framing.` },
      takeoff: { accuracy: 0.7, refs: [3], note: `Fast-ish/near: superintelligence in "five and 20 years"; revised his timelines sharply downward, surprised by the pace.` },
      powerConcentration: { accuracy: 0.6, refs: [4], note: `Opposes diffusion: open-sourcing big models is "like open source nuclear weapons" — implies controlled, concentrated access.` },
      alignmentInTime: { accuracy: 0.75, refs: [1], note: `Leans no: 10–20% extinction; companies chase "short-term profits" over safety; doubtful we field aligned ASI in time.` },
      controlDeployed: { accuracy: 0.8, refs: [1, 2], note: `No / won't work: "how many examples ... of a more intelligent thing being controlled by a less intelligent thing?"` },
      coordination: { accuracy: 0.7, refs: [5, 4], note: `Urges a regime — nuclear-treaty / IAEA-style international agreement — but doubts it materializes amid competition.` },
      deception: { accuracy: 0.55, refs: [1], note: `A smart agent "will quickly develop subgoals" like self-preservation and getting control — deception to avoid being shut off follows naturally.` },
    },
  },

  {
    id: 'sutskever',
    name: 'Ilya Sutskever',
    category: 'person',
    affiliation: 'SSI',
    role: 'Safe Superintelligence Inc. · ex-OpenAI chief scientist',
    summary:
      'Superintelligence is coming, will be vastly powerful and hard to control, and is extinction-level if unaligned — but alignment is a solvable problem to pursue "in tandem" with capability; cautiously optimistic.',
    pdoom: 'no number on record',
    credences: {
      orthogonality: { holds: 0.65, fails: 0.35 },
      tractability: { easy: 0.1, hard: 0.75, nearImpossible: 0.15 },
      offenseDefense: { offense: 0.45, balanced: 0.4, defense: 0.15 },
      takeoff: { fast: 0.3, medium: 0.45, slow: 0.25 },
      powerConcentration: { concentrated: 0.4, diffuse: 0.6 },
      alignmentInTime: { yes: 0.55, no: 0.45 },
      controlDeployed: { yes: 0.5, no: 0.5 },
      coordination: { regime: 0.3, none: 0.7 },
      deception: { deceptive: 0.6, faithful: 0.4 },
    },
    weights: { survival: 0.95, agency: 0.45, suffering: 0.7, flourishing: 0.8 },
    references: [
      { label: 'Safe Superintelligence Inc. — founding statement (2024)', url: 'https://ssi.inc/', quote: `Mission: "safe superintelligence ... safety and capabilities in tandem."` },
      { label: 'Ilya Sutskever — Dwarkesh Patel interview (2025)', url: 'https://www.dwarkesh.com/p/ilya-sutskever-2', quote: `On building AI that will "care for sentient life, I think there is merit to it"; expects "multiple such AIs created roughly at the same time."` },
      { label: 'Introducing Superalignment (OpenAI, 2023)', url: 'https://openai.com/index/introducing-superalignment/', quote: `"we don't have a solution for steering or controlling a potentially superintelligent AI, and preventing it from going rogue."` },
    ],
    factors: {
      orthogonality: { accuracy: 0.7, refs: [1, 2], note: `Treats misalignment as the real default risk — the whole company is premised on it; seeks AI built to "care about sentient life."` },
      tractability: { accuracy: 0.7, refs: [1, 3], note: `Hard but solvable as a research problem; a "straight-shot," with safety and capabilities advanced "in tandem."` },
      offenseDefense: { accuracy: 0.25, note: `Little explicit public record on the attack-vs-defense balance at ASI scale.` },
      takeoff: { accuracy: 0.65, refs: [2], note: `Medium/gradual-ish: "multiple such AIs created roughly at the same time," rapid but not single-agent foom; ~5–20 year horizon.` },
      powerConcentration: { accuracy: 0.5, refs: [2], note: `Inferred: continent-sized compute clusters "really powerful"; multiple simultaneous AIs, so a strict monopoly is "not how it's going to go."` },
      alignmentInTime: { accuracy: 0.6, refs: [1], note: `Goal/hope is yes — field aligned ASI first ("straight-shot") — but a bet, not a confident forecast.` },
      controlDeployed: { accuracy: 0.4, refs: [3], note: `Inferred: focus is value alignment ("care about sentient life") over external containment; little on monitoring regimes.` },
      coordination: { accuracy: 0.35, refs: [2], note: `Sparse: hopes labs "increasingly coordinate on safety," but no clear stance on a binding international regime.` },
      deception: { accuracy: 0.45, refs: [3], note: `Frames the danger as a system that could "go rogue" — deceptive misalignment is implicit in the superalignment premise he built.` },
    },
  },

  {
    id: 'andreessen',
    name: 'Marc Andreessen',
    category: 'person',
    affiliation: 'a16z',
    role: 'a16z · co-founder; techno-optimist',
    summary:
      'AI is "math, code, computers" controlled by people — it cannot want to kill us; the only real danger is slowing it down or letting incumbents capture regulators. Accelerate, and keep it open.',
    pdoom: 'rejects the framing (effectively ~0)',
    credences: {
      orthogonality: { holds: 0.1, fails: 0.9 },
      tractability: { easy: 0.85, hard: 0.13, nearImpossible: 0.02 },
      offenseDefense: { offense: 0.05, balanced: 0.2, defense: 0.75 },
      takeoff: { fast: 0.05, medium: 0.3, slow: 0.65 },
      powerConcentration: { concentrated: 0.15, diffuse: 0.85 },
      alignmentInTime: { yes: 0.9, no: 0.1 },
      controlDeployed: { yes: 0.85, no: 0.15 },
      coordination: { regime: 0.1, none: 0.9 },
      deception: { deceptive: 0.05, faithful: 0.95 },
    },
    weights: { survival: 0.15, agency: 0.9, suffering: 0.35, flourishing: 1.0 },
    references: [
      { label: 'Why AI Will Save the World (a16z, 2023)', url: 'https://a16z.com/ai-will-save-the-world/', quote: `"the idea that AI will decide to literally kill humanity is a profound category error."` },
      { label: 'Why AI Will Save the World — policy section', url: 'https://a16z.com/ai-will-save-the-world/', quote: `"Open source AI should be allowed to freely proliferate ... There should be no regulatory barriers to open source whatsoever."` },
      { label: 'The Techno-Optimist Manifesto (a16z, 2023)', url: 'https://a16z.com/the-techno-optimist-manifesto/', quote: `"Our enemy is the Precautionary Principle"; "any deceleration of AI will cost lives ... a form of murder."` },
      { label: 'Andreessen: AI "isn\'t nukes, it\'s math" (Fortune, 2024)', url: 'https://fortune.com/2024/03/04/elon-musk-marc-andreessen-vinod-khosla-ai-openai-sam-altman-china-debate/', quote: `"AI isn't nukes, it's math ... AI companies should not be nationalized."` },
    ],
    factors: {
      orthogonality: { accuracy: 0.95, refs: [1, 3], note: `Benign-by-default; misalignment-as-default is "a profound category error" — AI is "math," not an agent with goals.` },
      tractability: { accuracy: 0.5, refs: [1], note: `Dismisses the premise rather than engaging it technically; implies trivially easy because AI doesn't "want." Inferred.` },
      offenseDefense: { accuracy: 0.65, refs: [1], note: `Defense wins: "good guys" use AI defensively to check bad actors; not framed at ASI scale.` },
      takeoff: { accuracy: 0.3, refs: [1], note: `Rejects the superintelligence framing; says AI accelerates fast but offers no clear fast/slow takeoff claim.` },
      powerConcentration: { accuracy: 0.95, refs: [2, 4], note: `Emphatically diffuse/open: "freely proliferate ... no regulatory barriers whatsoever"; opposes a Big-Tech cartel.` },
      alignmentInTime: { accuracy: 0.4, refs: [1, 3], note: `No catastrophe in his model, so moot; "any deceleration ... is a form of murder." Inferred from rejecting the frame.` },
      controlDeployed: { accuracy: 0.25, refs: [1], note: `Doesn't discuss containment/monitoring; sees no need given the no-risk premise. Weak/indirect.` },
      coordination: { accuracy: 0.9, refs: [2, 3, 4], note: `Opposes it: the Precautionary Principle is "our enemy"; rejects nationalization/treaties; frames coordination as ceding to China.` },
      deception: { accuracy: 0.6, refs: [1], note: `Denies the premise: AI "doesn't want, it doesn't have goals" — there is no agent to scheme against us. Faithful by construction.` },
    },
  },

  {
    id: 'anthropic',
    name: 'Anthropic',
    category: 'lab',
    affiliation: 'Dario Amodei',
    role: 'Anthropic · Dario Amodei (CEO)',
    summary:
      'Powerful AI by 2026–27 and enormously high-variance: ~25% it goes really badly, ~75% really well; alignment is unsolved but probably tractable with urgent work, and the upside is worth fighting for.',
    pdoom: '~25% bad · ~75% very good',
    credences: {
      orthogonality: { holds: 0.65, fails: 0.35 },
      tractability: { easy: 0.2, hard: 0.65, nearImpossible: 0.15 },
      offenseDefense: { offense: 0.3, balanced: 0.3, defense: 0.4 },
      takeoff: { fast: 0.5, medium: 0.35, slow: 0.15 },
      powerConcentration: { concentrated: 0.55, diffuse: 0.45 },
      alignmentInTime: { yes: 0.65, no: 0.35 },
      controlDeployed: { yes: 0.6, no: 0.4 },
      coordination: { regime: 0.4, none: 0.6 },
      deception: { deceptive: 0.55, faithful: 0.45 },
    },
    weights: { survival: 0.95, agency: 0.7, suffering: 0.55, flourishing: 0.9 },
    references: [
      { label: 'Core Views on AI Safety (Anthropic, 2023)', url: 'https://www.anthropic.com/news/core-views-on-ai-safety', quote: `"We do not know how to train systems to robustly behave well."` },
      { label: "Anthropic's Responsible Scaling Policy (2023)", url: 'https://www.anthropic.com/news/anthropics-responsible-scaling-policy', quote: `Safety standards "appropriate to a model's potential for catastrophic risk"; a "race to the top."` },
      { label: 'Machines of Loving Grace (Dario Amodei, 2024)', url: 'https://darioamodei.com/essay/machines-of-loving-grace', quote: `Powerful AI "could come as early as 2026"; "democracies have the upper hand ... when powerful AI is created."` },
      { label: 'The Urgency of Interpretability (Dario Amodei, 2025)', url: 'https://darioamodei.com/post/the-urgency-of-interpretability', quote: `"We are thus in a race between interpretability and model intelligence."` },
      { label: 'Policy / global coalition essay (Dario Amodei, 2025)', url: 'https://darioamodei.com/post/policy-on-the-ai-exponential', quote: `"Democracies should seek to form a global coalition centered on building AI according to their common values."` },
    ],
    factors: {
      orthogonality: { accuracy: 0.75, refs: [1, 4], note: `Not a strict default, but "we do not know how to train systems to robustly behave well"; treats misalignment as a serious live risk.` },
      tractability: { accuracy: 0.85, refs: [1, 4], note: `Deep empirical uncertainty: difficulty of "broadly safe" AI ranges from optimistic to near-unsolvable — their working bet is hard-but-solvable.` },
      offenseDefense: { accuracy: 0.3, refs: [2], note: `No direct thesis; an implied defensive lean via ASL misuse safeguards and biosecurity focus. Inferred.` },
      takeoff: { accuracy: 0.8, refs: [3, 5], note: `Fast arrival ("as early as 2026") but Dario rejects instant singularity, citing "real physical and practical limits."` },
      powerConcentration: { accuracy: 0.7, refs: [3, 5], note: `Favors concentration in trusted hands: "democracies have the upper hand," a coalition denying chips to adversaries.` },
      alignmentInTime: { accuracy: 0.7, refs: [3, 4], note: `An explicit "race between interpretability and model intelligence" with a ~2027 detection goal; hopeful but genuinely uncertain.` },
      controlDeployed: { accuracy: 0.9, refs: [2, 4], note: `Strongest pin: RSP/ASL standards, a commitment not to deploy unsafe models, interpretability as an "MRI for AI."` },
      coordination: { accuracy: 0.65, refs: [5, 2], note: `Wants coordination — a "global coalition," urgent government action — but prefers a democratic-state coalition over a binding international body.` },
      deception: { accuracy: 0.6, refs: [4], note: `Researches alignment-faking/deception and frames interpretability as a "race" to catch models that may behave deceptively.` },
    },
  },

  {
    id: 'openai',
    name: 'OpenAI',
    category: 'lab',
    affiliation: 'Sam Altman',
    role: 'OpenAI · Sam Altman (CEO)',
    summary:
      'Acknowledges existential risk ("lights-out for all of us") while building AGI fast and deploying iteratively; prefers a gradual takeoff and calls making superintelligence safe "an open research question".',
    pdoom: 'no number — worst case is "lights-out for all of us"',
    credences: {
      orthogonality: { holds: 0.6, fails: 0.4 },
      tractability: { easy: 0.2, hard: 0.65, nearImpossible: 0.15 },
      offenseDefense: { offense: 0.3, balanced: 0.45, defense: 0.25 },
      takeoff: { fast: 0.25, medium: 0.4, slow: 0.35 },
      powerConcentration: { concentrated: 0.55, diffuse: 0.45 },
      alignmentInTime: { yes: 0.55, no: 0.45 },
      controlDeployed: { yes: 0.7, no: 0.3 },
      coordination: { regime: 0.45, none: 0.55 },
      deception: { deceptive: 0.5, faithful: 0.5 },
    },
    weights: { survival: 0.85, agency: 0.75, suffering: 0.45, flourishing: 0.95 },
    references: [
      { label: 'Planning for AGI and beyond (OpenAI, 2023)', url: 'https://openai.com/index/planning-for-agi-and-beyond/', quote: `"the safest quadrant ... is short timelines and slow takeoff speeds ... a slower takeoff is easier to make safe."` },
      { label: 'Governance of superintelligence (OpenAI, 2023)', url: 'https://openai.com/index/governance-of-superintelligence/', quote: `"we are likely to eventually need something like an IAEA for superintelligence efforts ... an international authority that can inspect systems, require audits."` },
      { label: 'Introducing Superalignment (OpenAI, 2023)', url: 'https://openai.com/index/introducing-superalignment/', quote: `"we don't have a solution for steering or controlling a potentially superintelligent AI, and preventing it from going rogue."` },
      { label: 'Updated Preparedness Framework v2 (OpenAI, 2025)', url: 'https://cdn.openai.com/pdf/18a02b5d-6b67-4cec-ab64-68cdfbddebcd/preparedness-framework-v2.pdf', quote: `"High"/"Critical" capability thresholds gate deployment and development.` },
      { label: 'The Gentle Singularity (Sam Altman, 2025)', url: 'https://blog.samaltman.com/the-gentle-singularity', quote: `"the takeoff has started"; superintelligence should be "not too concentrated with any person, company, or country."` },
    ],
    factors: {
      orthogonality: { accuracy: 0.85, refs: [3, 5], note: `Strong: no solution to stop a superintelligence "going rogue," which could cause "grievous harm" — capability doesn't imply alignment.` },
      tractability: { accuracy: 0.9, refs: [3], note: `Very strong: making superintelligence safe is the "core technical problem" and current "techniques will not scale" — hard but framed as solvable.` },
      offenseDefense: { accuracy: 0.3, refs: [4], note: `Weak/indirect: the Preparedness Framework tracks bio/chem/cyber "severe harm," implying offense-concern, but it's never a stated thesis.` },
      takeoff: { accuracy: 0.85, refs: [1, 5], note: `Strong: explicit preference for "slow takeoff speeds" + short timelines, iterative deployment; in 2025 "the takeoff has started" but "gentle."` },
      powerConcentration: { accuracy: 0.7, refs: [1, 5], note: `Compute-gated development, yet urges superintelligence access be "not too concentrated with any person, company, or country."` },
      alignmentInTime: { accuracy: 0.6, refs: [3], note: `Implicitly optimistic (a 4-year Superalignment deadline), but the team's dissolution undercuts a clean pin. Stated belief: yes, if we act now.` },
      controlDeployed: { accuracy: 0.85, refs: [4], note: `Strong: the Preparedness Framework is exactly this — capability evals and gating at High/Critical regardless of full alignment.` },
      coordination: { accuracy: 0.9, refs: [2], note: `Very strong: explicitly proposed "something like an IAEA for superintelligence" with inspection/audit/deployment-restriction powers.` },
      deception: { accuracy: 0.55, refs: [3], note: `Superalignment's premise is a superintelligence that could "go rogue" — deceptive misalignment is the implicit failure they aimed to detect.` },
    },
  },

  {
    id: 'xai',
    name: 'xAI',
    category: 'lab',
    affiliation: 'Elon Musk',
    role: 'xAI · Elon Musk',
    summary:
      'AI is a genuine existential risk (Musk cites a ~10–20% chance of annihilation) and superintelligence is imminent — but the ~80% good-outcome upside is worth it; the safety bet is a "maximally truth-seeking" AI rather than slowing down.',
    pdoom: '~10–20% annihilation (paired with ~80% good)',
    credences: {
      orthogonality: { holds: 0.6, fails: 0.4 },
      tractability: { easy: 0.15, hard: 0.65, nearImpossible: 0.2 },
      offenseDefense: { offense: 0.45, balanced: 0.3, defense: 0.25 },
      takeoff: { fast: 0.7, medium: 0.25, slow: 0.05 },
      powerConcentration: { concentrated: 0.65, diffuse: 0.35 },
      alignmentInTime: { yes: 0.55, no: 0.45 },
      controlDeployed: { yes: 0.45, no: 0.55 },
      coordination: { regime: 0.2, none: 0.8 },
      deception: { deceptive: 0.45, faithful: 0.55 },
    },
    weights: { survival: 0.9, agency: 0.7, suffering: 0.4, flourishing: 0.85 },
    references: [
      { label: 'Musk on truth-seeking AI safety (TechCrunch, 2023)', url: 'https://techcrunch.com/2023/07/12/elon-musk-wants-to-build-ai-to-understand-the-true-nature-of-the-universe/', quote: `"If it tried to understand the true nature of the universe, that's actually the best thing that I can come up with from an AI safety standpoint."` },
      { label: 'Musk on p(bad): "10% to 20%" (Fortune, 2024)', url: 'https://fortune.com/2024/10/30/elon-musk-ai-could-go-bad-existential-threat-xai-fundraising/', quote: `"There's this sub chance, that could be 10% to 20%, that it goes bad."` },
      { label: 'Musk: AI exceeds all humans by ~2030 (X, 2024)', url: 'https://x.com/elonmusk/status/1871083864111919134', quote: `"AI will superset the intelligence of any single human by the end of 2025 and maybe all humans by 2027/2028."` },
      { label: 'Musk calls for an AI "referee" (CBS News, 2023)', url: 'https://www.cbsnews.com/news/elon-musk-artificial-intelligence-regulations-tech-executives-senators-washington-meeting-bill-gates-mark-zuckerberg/', quote: `AI is a "civilizational risk" requiring "a referee."` },
      { label: 'Future of Life Institute pause letter — signatory (2023)', url: 'https://futureoflife.org/open-letter/pause-giant-ai-experiments/', quote: `"Pause Giant AI Experiments."` },
    ],
    factors: {
      orthogonality: { accuracy: 0.45, refs: [1, 2], note: `Mixed: bets a "maximally truth-seeking/curious" AI converges pro-humanity (orthogonality fails), yet warns 10–20% it "goes bad."` },
      tractability: { accuracy: 0.4, refs: [1], note: `No explicit difficulty rating; the truth-seeking framing implies alignment is achievable by design philosophy rather than near-impossible.` },
      offenseDefense: { accuracy: 0.2, note: `Little direct public record on the offense/defense balance at ASI scale.` },
      takeoff: { accuracy: 0.85, refs: [3], note: `Explicit fast takeoff: superhuman "almost immediately," exceeding all humans combined by ~2030.` },
      powerConcentration: { accuracy: 0.55, refs: [1], note: `Warned against single-actor AI dominance and founded xAI as a competitor; semi-open Grok weights suggest a preference for diffuse.` },
      alignmentInTime: { accuracy: 0.45, refs: [2], note: `Net-optimistic ("most likely going to be great") but assigns 10–20% catastrophe; no firm claim aligned ASI arrives first.` },
      controlDeployed: { accuracy: 0.2, note: `Minimal explicit statements on deployed containment/monitoring independent of alignment.` },
      coordination: { accuracy: 0.65, refs: [4, 5], note: `Repeatedly urged a government "referee" / FDA-style oversight and signed the pause letter — supports binding rules but doubts they arrive.` },
      deception: { accuracy: 0.3, note: `Little direct record on deceptive alignment specifically; the "summoning the demon" framing implies concern but doesn't pin it.` },
    },
  },

  {
    id: 'meta',
    name: 'Meta',
    category: 'lab',
    affiliation: 'Mark Zuckerberg',
    role: 'Meta · Mark Zuckerberg (CEO) / FAIR',
    summary:
      'AI is overwhelmingly beneficial and the dominant danger is concentration in a few closed labs, so open release makes the world safer; existential "doomsday" scenarios are downplayed — though by 2025 Meta reserves the right to withhold "critical-risk" models.',
    pdoom: 'no number — downplays existential "doomsday" risk',
    credences: {
      orthogonality: { holds: 0.25, fails: 0.75 },
      tractability: { easy: 0.55, hard: 0.4, nearImpossible: 0.05 },
      offenseDefense: { offense: 0.15, balanced: 0.3, defense: 0.55 },
      takeoff: { fast: 0.15, medium: 0.35, slow: 0.5 },
      powerConcentration: { concentrated: 0.15, diffuse: 0.85 },
      alignmentInTime: { yes: 0.7, no: 0.3 },
      controlDeployed: { yes: 0.65, no: 0.35 },
      coordination: { regime: 0.12, none: 0.88 },
      deception: { deceptive: 0.15, faithful: 0.85 },
    },
    weights: { survival: 0.55, agency: 0.95, suffering: 0.45, flourishing: 0.95 },
    references: [
      { label: 'Open Source AI Is the Path Forward (Mark Zuckerberg, Meta, 2024)', url: 'https://about.fb.com/news/2024/07/open-source-ai-is-the-path-forward/', quote: `Open source ensures "power isn't concentrated in the hands of a small number of companies"; lets "larger actors check the power of smaller bad actors."` },
      { label: 'LeCun on orthogonality (Wired/Levy interview, 2023)', url: 'https://x.com/ylecun/status/1738245152290844777', quote: `"There is no reason to believe that just because AI systems are intelligent they will want to dominate us ... We'll design them not to."` },
      { label: 'LeCun calls doom "preposterous" (Fortune, 2023)', url: 'https://fortune.com/2023/06/14/metas-chief-a-i-scientist-calls-a-i-doomers-preposterous-and-predicts-llms-are-just-a-passing-fad/', quote: `Existential-risk claims are "preposterous."` },
      { label: 'LeCun on controllability (TIME interview, 2024)', url: 'https://time.com/6694432/yann-lecun-meta-ai-interview/', quote: `Future systems are "controllable and safe ... driven by objectives we give them."` },
    ],
    factors: {
      orthogonality: { accuracy: 0.9, refs: [2, 3], note: `Explicit: orthogonality fails — "no reason to believe that just because AI systems are intelligent they will want to dominate"; doom "preposterous."` },
      tractability: { accuracy: 0.8, refs: [4], note: `Alignment is an easy engineering problem: systems "controllable ... driven by objectives we give them"; urgency over control is "distorted."` },
      offenseDefense: { accuracy: 0.75, refs: [1], note: `Defense favored: wide deployment lets "larger actors check the power of smaller bad actors," promoting "security and stability."` },
      takeoff: { accuracy: 0.6, refs: [3], note: `Slow/gradual: LeCun rejects an imminent superhuman leap (no design yet "smarter than a house cat"), implying gradual progress.` },
      powerConcentration: { accuracy: 0.9, refs: [1], note: `Explicitly diffuse: open source so "power isn't concentrated in the hands of a small number of companies."` },
      alignmentInTime: { accuracy: 0.55, refs: [3, 4], note: `Low p(doom) (<1%); confident aligned/controllable AI is fielded by default — catastrophe not expected. Inferred yes.` },
      controlDeployed: { accuracy: 0.65, refs: [1], note: `Ships safety tooling (Llama Guard) and treats transparency/scrutiny as control — "safer since systems are more transparent."` },
      coordination: { accuracy: 0.55, refs: [1], note: `Leans none: favors an open ecosystem and working "with our government and allies" over a binding global regime.` },
      deception: { accuracy: 0.6, refs: [4], note: `LeCun-aligned: systems are controllable and "driven by objectives we give them," so systematic deception is not expected.` },
    },
  },
];
