/**
 * actionConditions prototype → docs/ACTION-CONDITIONS.md
 *
 * The INVERSE of "given beliefs, what action?" — for each action, under what
 * conditions is it the one to pursue?
 *
 * Method (see the design note in chat): the "conditions" are the factors NO action
 * can move — the five OBJECTIVE factors (orthogonality, tractability, offense/defense,
 * takeoff, deception). Every action moves only non-objective factors, so conditioning
 * on the objective ones leaves every action room to act, apples-to-apples. For each
 * objective-world w (a joint assignment of the 5, weighted by its coupled prior) we
 * compute each action's conditional-mean EV gain, then ask where action A is the
 * *best* lever — A vs. the best alternative (including "do nothing" = 0), because
 * every action beats nothing almost everywhere, so "A vs nothing" is uninformative.
 *
 * Outputs per action: the share of worlds where it's the best lever, a crux tornado
 * (which objective question most flips whether A is best), and the top favorable /
 * unfavorable conditions. This is a script prototype; if the shape is right it graduates
 * to an "action mode" on the Conditions tab (reusing the tornado / heatmap / threshold
 * viz). Regenerate with:
 *   pnpm exec vitest run --config scripts/findings.config.ts
 */
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { test } from 'vitest';
import { dataset } from '@model/dataset';
import { applyAction } from '@engine/index';
import {
  actionLabel,
  base,
  condMean,
  docLines,
  factorLabel,
  objectiveWorlds,
  pct,
  sev,
  stateLabel,
} from './lib';

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), '../docs/ACTION-CONDITIONS.md');

const objectives = dataset.factors.filter((f) => f.kind === 'objective');
const objIds = objectives.map((f) => f.id);

// ── the objective-world distribution (the "conditions" space) ────────────────
const { worlds, worldProb, worldPins } = objectiveWorlds();

// gain[actionId][world] = conditional-mean EV improvement of that action in that world
const baseByWorld: Record<string, number> = {};
for (const w of worlds) baseByWorld[w] = condMean(base, worldPins[w]);
const gain: Record<string, Record<string, number>> = {};
for (const a of dataset.actions) {
  gain[a.id] = {};
  for (const w of worlds) gain[a.id][w] = condMean(applyAction(base, a), worldPins[w]) - baseByWorld[w];
}

/** In world w, is action A the best lever? (A vs best alternative, floored at do-nothing.) */
function marginOf(aid: string, w: string): number {
  let bestOther = 0; // "do nothing" = 0
  for (const b of dataset.actions) if (b.id !== aid) bestOther = Math.max(bestOther, gain[b.id][w]);
  return gain[aid][w] - bestOther;
}

const { P, save } = docLines();

P('# Under what conditions should I pursue each action?');
P();
P('> Auto-generated by [`scripts/action-conditions.ts`](../scripts/action-conditions.ts).');
P('> Regenerate: `pnpm exec vitest run --config scripts/findings.config.ts`.');
P('>');
P('> The inverse of the "where to act" tornado: for each action, the region of');
P('> conditions where it is the **best lever to pursue** (vs. the best alternative,');
P('> floored at doing nothing). Conditions = the 5 objective factors (the exogenous');
P('> facts no action can move). Independence × couplings model (the app defaults to the Bayes net) + cached value surface.');
P();
P('**How to read a crux table:** each row is an objective question; the cells show, for');
P('each of its answers, the *share of that answer\'s worlds where this action is best* and');
P('the *mean margin* over the next-best alternative (positive = this action wins). A row');
P('whose win-share crosses 50% across answers is a **verdict-flipper** — that question');
P('decides whether to pursue the action.');
P();

// Overall win-shares.
const winShare: Record<string, number> = {};
const worthShare: Record<string, number> = {};
for (const a of dataset.actions) {
  let win = 0;
  let worth = 0;
  for (const w of worlds) {
    if (marginOf(a.id, w) > 1e-9) win += worldProb[w];
    if (gain[a.id][w] > 1e-9) worth += worldProb[w];
  }
  winShare[a.id] = win;
  worthShare[a.id] = worth;
}
const ranked = [...dataset.actions].sort((x, y) => winShare[y.id] - winShare[x.id]);

P('## Summary: how often is each action the best lever?');
P();
P('| Action | best lever in | positive gain in |');
P('|---|---:|---:|');
for (const a of ranked) P(`| ${a.label} | **${pct(winShare[a.id])}** | ${pct(worthShare[a.id])} |`);
P();
P('The best-lever shares sum to ~100% (one action wins each world). "Positive gain" can exceed it — several actions help a world; only one is *best*.');
P();

// ── per-action detail ────────────────────────────────────────────────────────
for (const a of ranked) {
  P('---');
  P();
  P(`## ${a.label}`);
  P();
  P(`Best lever in **${pct(winShare[a.id])}** of objective worlds · moves ${a.deltas.map((d) => `${factorLabel(d.factor)}→${stateLabel(d.factor, d.towardState)}`).join(', ')}.`);
  P();

  // Crux table: per objective factor, per state, win-share + mean margin.
  type CruxRow = { fid: string; span: number; flips: boolean; cells: { s: string; winShare: number; meanMargin: number }[] };
  const cruxes: CruxRow[] = objectives.map((f) => {
    const cells = f.states.map((st) => {
      let mass = 0;
      let winMass = 0;
      let marginSum = 0;
      for (const w of worlds) {
        if (worldPins[w][f.id] !== st.id) continue;
        const p = worldProb[w];
        mass += p;
        marginSum += p * marginOf(a.id, w);
        if (marginOf(a.id, w) > 1e-9) winMass += p;
      }
      return { s: st.id, winShare: mass > 0 ? winMass / mass : 0, meanMargin: mass > 0 ? marginSum / mass : 0 };
    });
    const margins = cells.map((c) => c.meanMargin);
    const shares = cells.map((c) => c.winShare);
    return {
      fid: f.id,
      span: Math.max(...margins) - Math.min(...margins),
      flips: Math.max(...shares) > 0.5 && Math.min(...shares) <= 0.5,
      cells,
    };
  });
  cruxes.sort((x, y) => y.span - x.span);

  const top = cruxes[0];
  const topBestState = top.cells.reduce((m, c) => (c.meanMargin > m.meanMargin ? c : m));
  const topWorstState = top.cells.reduce((m, c) => (c.meanMargin < m.meanMargin ? c : m));
  if (winShare[a.id] > 0.5) {
    P(`**Verdict:** the default priority. It yields the top slot mainly when **${factorLabel(top.fid)} = ${stateLabel(top.fid, topWorstState.s)}** (best-lever share drops to ${pct(topWorstState.winShare)} there).`);
  } else if (winShare[a.id] > 0) {
    P(`**Verdict:** a *conditional* priority — pursue it when **${factorLabel(top.fid)} = ${stateLabel(top.fid, topBestState.s)}** (best-lever share ${pct(topBestState.winShare)}); otherwise a lower priority.`);
  } else {
    P('**Verdict:** never the single best lever in this model — another action always beats it. (Its gain may still be positive; it just never tops the field.)');
  }
  P();
  P('| Crux (objective question) | answer | best-lever share | mean margin | flips? |');
  P('|---|---|---:|---:|:---:|');
  for (const cr of cruxes.slice(0, 3)) {
    cr.cells.forEach((c, i) => {
      P(`| ${i === 0 ? factorLabel(cr.fid) : ''} | ${stateLabel(cr.fid, c.s)} | ${pct(c.winShare)} | ${sev(c.meanMargin)} | ${i === 0 ? (cr.flips ? '**yes**' : 'no') : ''} |`);
    });
  }
  P();

  // Favorable / unfavorable single conditions (by mean margin across all (F,s)).
  const conds: { label: string; margin: number }[] = [];
  for (const f of objectives) {
    for (const st of f.states) {
      let mass = 0;
      let marginSum = 0;
      for (const w of worlds) {
        if (worldPins[w][f.id] !== st.id) continue;
        mass += worldProb[w];
        marginSum += worldProb[w] * marginOf(a.id, w);
      }
      conds.push({ label: `${factorLabel(f.id)} = ${stateLabel(f.id, st.id)}`, margin: mass > 0 ? marginSum / mass : 0 });
    }
  }
  conds.sort((x, y) => y.margin - x.margin);
  const favs = conds.filter((c) => c.margin > 0).slice(0, 3);
  const unfavs = conds.filter((c) => c.margin < 0).slice(-3).reverse();
  if (favs.length) P(`**Most favorable conditions:** ${favs.map((c) => `${c.label} (${sev(c.margin)})`).join('; ')}.`);
  if (unfavs.length) P(`**Least favorable:** ${unfavs.map((c) => `${c.label} (${sev(c.margin)})`).join('; ')}.`);
  P();
}

P('---');
P();
P('*Prototype. Caveat from the findings: the actions are largely correlated, so several have small or empty best-lever regions — the output reads "pursue A only when [narrow crux]." That is the honest answer, and also the case for designing more differentiated actions (adding the open-source/antitrust lever, for instance, is what gives orthogonality a top-action flip). Conditioning is on objective factors only; a fuller version would also let you condition on the influenceable/contingent factors an action doesn\'t itself move.*');

test('action conditions → docs/ACTION-CONDITIONS.md', () => {
  save(OUT);
});
