/**
 * Findings miner — sweeps the value/probability models for *surprising*, decision-
 * relevant results and writes them to docs/FINDINGS.md.
 *
 * It's wired as a one-off vitest "test" purely so it can import the engine through
 * the @-aliases (see scripts/findings.config.ts). It asserts nothing about the app;
 * it just computes and writes. Regenerate with:
 *   pnpm exec vitest run --config scripts/findings.config.ts
 *
 * Everything here reads the *default* probability model (independence × couplings),
 * the same one the app shows by default, and the *cached* (hand-reasoned) value
 * surface. Numbers move whenever dataset.ts is re-authored — that's expected; rerun.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { test } from 'vitest';
import { dataset } from '@model/dataset';
import {
  analyze,
  applyAction,
  cachedEvaluator,
  rankActions,
  scalarize,
  sensitivity,
  enumerateScenarios,
  type Analysis,
  type Pins,
} from '@engine/index';
import type { Credences, ValueVector } from '@model/types';

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), '../docs/FINDINGS.md');

const base = dataset.baselineCredences;
const W = dataset.defaultWeights;
const ev = cachedEvaluator;

// ── helpers ────────────────────────────────────────────────────────────────
const pct = (x: number) => `${(x * 100).toFixed(1)}%`;
const sev = (x: number) => `${x >= 0 ? '+' : '−'}${Math.abs(x).toFixed(3)}`;
const actionLabel = (id: string) => dataset.actions.find((a) => a.id === id)?.label ?? id;

function weights(partial: Partial<ValueVector>): ValueVector {
  return { survival: 0, agency: 0, suffering: 0, flourishing: 0, ...partial };
}

/** A copy of the baseline credences with one factor forced ~certain to a state. */
function believe(factorId: string, stateId: string, p = 0.98): Credences {
  const c: Credences = structuredClone(base);
  const dist = c[factorId];
  const others = Object.keys(dist).filter((s) => s !== stateId);
  const rem = 1 - p;
  const priorOthers = others.reduce((a, s) => a + dist[s], 0);
  c[factorId] = { [stateId]: p } as Record<string, number>;
  for (const s of others) c[factorId][s] = priorOthers > 0 ? rem * (dist[s] / priorOthers) : rem / others.length;
  return c;
}

/** Probability mass on catastrophic corners of each value dimension. */
function tailMass(a: Analysis) {
  const m = { extinction: 0, srisk: 0, agencyLoss: 0, squandered: 0 };
  for (const s of a.scenarios) {
    if (s.value.survival < -0.5) m.extinction += s.probability;
    if (s.value.suffering < -0.5) m.srisk += s.probability;
    if (s.value.agency < -0.5) m.agencyLoss += s.probability;
    if (s.value.flourishing < -0.5) m.squandered += s.probability;
  }
  return m;
}

/** Top action + its gain under a given credence set & weights. */
function topAction(cred: Credences, w: ValueVector) {
  const { ranked } = rankActions(dataset, cred, w, ev);
  return ranked[0];
}

const lines: string[] = [];
const P = (s = '') => lines.push(s);

// ── header ───────────────────────────────────────────────────────────────
P('# Surprising findings');
P();
P('> Auto-generated by [`scripts/mine-findings.ts`](../scripts/mine-findings.ts).');
P('> Regenerate: `pnpm exec vitest run --config scripts/findings.config.ts`.');
P('>');
P('> All numbers use the **default** probability model (independence × couplings) and the');
P('> **cached** (hand-reasoned) value surface. Everything is a *presumed first-pass model* —');
P('> these are properties of the current `dataset.ts`, not claims about the real world. The');
P('> point is the *shape* of the reasoning: where the model says something non-obvious.');
P();

// ── baseline reference ─────────────────────────────────────────────────────
const baseA = analyze(dataset, base, W, ev);
const baseTail = tailMass(baseA);
const baseRank = rankActions(dataset, base, W, ev).ranked;
P('## The baseline, for reference');
P();
P(`At the default beliefs and default weights (survival ${W.survival}, suffering ${W.suffering}, agency ${W.agency}, flourishing ${W.flourishing}):`);
P();
P(`- **Expected value:** ${sev(baseA.ev)} (scale −1…+1)`);
P(`- **Extinction mass** P(survival < −0.5): **${pct(baseTail.extinction)}** · **s-risk mass** P(suffering < −0.5): **${pct(baseTail.srisk)}** · **agency-loss mass** P(agency < −0.5): **${pct(baseTail.agencyLoss)}**`);
P('- **Action ranking (EV gain vs. no action):**');
P();
P('  | rank | action | EV gain |');
P('  |---|---|---:|');
baseRank.forEach((r, i) => P(`  | ${i + 1} | ${r.action.label} | ${sev(r.evGain)} |`));
P();
const baseTop = baseRank[0].action.id;
const baseSecond = baseRank[1].action.id;
P(`So the headline lever is **${actionLabel(baseTop)}**, with **${actionLabel(baseSecond)}** as runner-up.`);
P();

// ═══════════════════════════════════════════════════════════════════════════
// Precompute the quantities the headline surprises reference.
const sensAll = sensitivity(dataset, base, W, ev).sort((a, b) => b.swing - a.swing);
const orthVoI = sensAll.find((r) => r.factorId === 'orthogonality')?.swing ?? 0;
const powerSwing = sensAll.find((r) => r.factorId === 'powerConcentration')?.swing ?? 0;
const deceptionVoI = sensAll.find((r) => r.factorId === 'deception')?.swing ?? 0;
const aniGain = topAction(believe('tractability', 'nearImpossible'), W).evGain; // "alignment near-impossible"
const aeGain = topAction(believe('tractability', 'easy'), W).evGain; // "alignment easy"
const bestActionGain = baseRank[0].evGain;
// Which beliefs push the runner-up OFF control (usually onto coordination)?
const secondFlipBeliefs: string[] = [];
for (const b of [
  { name: 'deception is the default', factor: 'deception', state: 'deceptive' },
  { name: 'offense dominates', factor: 'offenseDefense', state: 'offense' },
]) {
  const r = rankActions(dataset, believe(b.factor, b.state), W, ev).ranked;
  if (r[1].action.id !== baseSecond) secondFlipBeliefs.push(`${b.name} → ${r[1].action.label}`);
}

// Power concentration: the marginal tornado hides a per-dimension + conditional effect.
const agencyW = weights({ agency: 1 });
const sensAgency = sensitivity(dataset, base, agencyW, ev).sort((a, b) => b.swing - a.swing);
const powerAgencyRank = sensAgency.findIndex((r) => r.factorId === 'powerConcentration') + 1;
const powerAgencySwing = sensAgency.find((r) => r.factorId === 'powerConcentration')?.swing ?? 0;
/** Normalized conditional-mean EV (not mass-weighted). */
function condMeanEV(pins: Pins, w: ValueVector): number {
  const a = analyze(dataset, base, w, ev, pins);
  return a.totalProbability > 0 ? a.ev / a.totalProbability : 0;
}
/** concentrated − diffuse conditional-mean EV under weights w and an extra condition. */
function powerGap(cond: Pins, w: ValueVector): number {
  return condMeanEV({ ...cond, powerConcentration: 'concentrated' }, w) - condMeanEV({ ...cond, powerConcentration: 'diffuse' }, w);
}

// Deception flips SIGN by régime: catastrophic everywhere except the benign attractor.
function cornerOf(s: Parameters<typeof ev.evaluate>[0]): string {
  if (s.orthogonality === 'fails') return 'benign';
  if (s.alignmentInTime === 'yes') return 'aligned';
  if (s.controlDeployed === 'yes') return 'control';
  return 'doom';
}
const decByCorner: Record<string, { sum: number; n: number }> = {};
for (const s of enumerateScenarios(dataset.factors)) {
  if (s.deception !== 'faithful') continue;
  const f = scalarize(ev.evaluate(s, dataset)!.value, W);
  const d = scalarize(ev.evaluate({ ...s, deception: 'deceptive' }, dataset)!.value, W);
  const c = cornerOf(s);
  (decByCorner[c] ??= { sum: 0, n: 0 }).sum += d - f;
  decByCorner[c].n++;
}
const decGap = (c: string) => (decByCorner[c] ? decByCorner[c].sum / decByCorner[c].n : 0);

P('## Headline surprises');
P();
P('The full tables are below; these are the results that most defy first intuition.');
P();
P(`1. **The #1 action never changes — and that itself is the warning.** Across every value profile (§1) and every forced belief (§2), *${actionLabel(baseTop)}* stays the top lever. A recommendation that survives believing alignment is near-impossible, that takeoff is fast, that deception is default, *and* the opposite of each is not robustness — it's a sign the action set is too coarse. Three of the four actions ultimately push the same two downstream factors (control/coordination), and the fourth moves the single highest-leverage factor, so it wins by construction. **Read this as "add more differentiated actions," not "the answer is settled."**`);
P();
P(`2. **Funding alignment scores _highest_ exactly when you believe alignment is hardest.** Convinced it's near-impossible → EV gain **${sev(aniGain)}**; convinced it's easy → only **${sev(aeGain)}**. Backwards on its face. The mechanism: the modeled action moves *alignment-deployed-in-time*, which the model treats as decoupled from intrinsic *tractability*, and near-impossible worlds have the worst baseline (most headroom). **This is a genuine model artifact worth fixing** — an action that "funds alignment" should plausibly be gated by tractability. Flagged, not hidden.`);
P();
P(`3. **The most decision-relevant question in the whole model is one nobody can act on.** The Orthogonality Thesis has the largest EV swing of anything — **${orthVoI.toFixed(3)}**, larger than the best *action's* gain of ${sev(bestActionGain)}. Resolving whether misalignment is the default is worth more than any intervention. Deceptive-alignment is close behind (${deceptionVoI.toFixed(3)}). The highest-value moves here are *research/forecasting*, not deployment.`);
P();
if (secondFlipBeliefs.length) {
  P(`4. **What comes _second_ does flip on your beliefs — control vs. coordination.** The default runner-up is *${actionLabel(baseSecond)}*, but ${secondFlipBeliefs.join('; ')}. Intuitively right and easy to miss: if you expect systems to deceive oversight, *control* (which relies on trustworthy evaluation) loses its edge to *coordination* (which buys time upstream).`);
  P();
}
P(`5. **The tornado calls power concentration inert (swing ${powerSwing.toFixed(3)}) — that's the *metric* lying, not the factor.** The marginal, survival-weighted swing collapses for three reasons: it's *moot in doom worlds* (~40% of the mass — a misaligned takeover moots who held power beforehand), *sign-split* elsewhere (concentration buys survival-safety but costs agency), and the tornado is *mass-weighted*. Change the lens and it roars back: on the **agency** dimension alone it is the **#${powerAgencyRank}** most decisive factor of all (swing ${powerAgencySwing.toFixed(3)}, up from dead last), and *conditional* on a survivable world its concentrated−diffuse gap is many times the marginal (§7). Power concentration matters exactly where intuition says — under slow takeoff, under governance, in worlds we survive — the default view just averages it away.`);
P();
P(`6. **Deception is catastrophic in every régime but one — where it's mildly *good*.** Averaged within each logical corner, switching faithful → deceptive changes value by **${sev(decGap('benign'))}** in the **benign** corner (orthogonality fails) but ${sev(decGap('aligned'))} in ALIGNED and ${sev(decGap('control'))} in CONTROL worlds. Deception is the only factor that flips *sign* on the régime: when capable systems are benign by default, a system that "masks under evaluation" is scheming about nothing — the deception is moot, even marginally friction-reducing. The benign effect is tiny (one +0.02 suffering nudge, worth a sanity check) but the structure is the point — **deception's harm is entirely contingent on the orthogonality thesis holding.** If you were sure of a benign attractor, deceptive alignment would drop off the worry list.`);
P();

// ═══════════════════════════════════════════════════════════════════════════
P('---');
P();
P('## 1. What you care about changes what you should do');
P();
P('Re-rank the actions under different value weightings — someone who only wants to *avoid extinction* vs. someone who only wants to *avoid astronomical suffering* (s-risk) vs. only *self-determination* (agency). The #1 lever holds, but the **runner-up** shifts: an s-risk-focused funder\'s _second_ priority is coordination, a survival-focused one\'s is control. That second choice is the genuine values-driven fork.');
P();
const profiles: { name: string; w: ValueVector; note: string }[] = [
  { name: 'Survival only', w: weights({ survival: 1 }), note: 'all that matters is that humanity persists' },
  { name: 'Suffering only (s-risk)', w: weights({ suffering: 1 }), note: 'all that matters is avoiding astronomical suffering' },
  { name: 'Agency only', w: weights({ agency: 1 }), note: 'all that matters is avoiding lock-in / tyranny' },
  { name: 'Flourishing only', w: weights({ flourishing: 1 }), note: 'all that matters is realizing our potential' },
  { name: 'S-risk-averse', w: weights({ survival: 0.35, suffering: 0.65 }), note: 'survival matters, but a bad survival is worse than none' },
];
P('| If you care about… | Top action | EV gain | Runner-up | Runner-up flips? |');
P('|---|---|---:|---|:---:|');
for (const prof of profiles) {
  const { ranked } = rankActions(dataset, base, prof.w, ev);
  const flip2 = ranked[1].action.id !== baseSecond;
  P(`| ${prof.name} | **${ranked[0].action.label}** | ${sev(ranked[0].evGain)} | ${ranked[1].action.label} | ${flip2 ? '**YES**' : 'no'} |`);
}
P();
P(`*Baseline: #1 = ${actionLabel(baseTop)}, #2 = ${actionLabel(baseSecond)}. The #1 never flips on values; the runner-up sometimes does — that's the real values-driven fork.*`);
P();

// ═══════════════════════════════════════════════════════════════════════════
P('---');
P();
P('## 2. What you believe changes what you should do');
P();
P('Now hold the values at default and instead force one belief to near-certainty. This answers "*given that you\'re convinced of X, what\'s the best lever?*" — including the case where you think the headline lever is hopeless.');
P();
const beliefs: { name: string; factor: string; state: string }[] = [
  { name: 'Alignment is near-impossible', factor: 'tractability', state: 'nearImpossible' },
  { name: 'Alignment is easy', factor: 'tractability', state: 'easy' },
  { name: 'Orthogonality fails (benign by default)', factor: 'orthogonality', state: 'fails' },
  { name: 'Takeoff will be fast', factor: 'takeoff', state: 'fast' },
  { name: 'Takeoff will be slow', factor: 'takeoff', state: 'slow' },
  { name: 'Deception is the default', factor: 'deception', state: 'deceptive' },
  { name: 'Systems will be faithful', factor: 'deception', state: 'faithful' },
  { name: 'Power will be concentrated', factor: 'powerConcentration', state: 'concentrated' },
  { name: 'Power will be diffuse', factor: 'powerConcentration', state: 'diffuse' },
  { name: 'Offense dominates', factor: 'offenseDefense', state: 'offense' },
];
P('| If you\'re convinced… | Top action | EV gain | Runner-up | Runner-up flips? |');
P('|---|---|---:|---|:---:|');
for (const b of beliefs) {
  const cred = believe(b.factor, b.state);
  const { ranked } = rankActions(dataset, cred, W, ev);
  const flip2 = ranked[1].action.id !== baseSecond;
  P(`| ${b.name} | **${ranked[0].action.label}** | ${sev(ranked[0].evGain)} | ${ranked[1].action.label} | ${flip2 ? '**YES**' : 'no'} |`);
}
P();
P(`*Note the paradox in the first two rows: ${actionLabel(baseTop)} gains **more** when you believe alignment is near-impossible than when you believe it's easy — see Headline surprise #2.*`);
P();

// ═══════════════════════════════════════════════════════════════════════════
P('---');
P();
P('## 3. Every action is a trade-off across the value dimensions');
P();
P('EV gain hides *which* dimension an action buys and whether it costs another. For each action, the change in each catastrophic-tail mass vs. baseline (negative = the action *shrinks* that risk; positive = it *grows* it):');
P();
P('| Action | ΔEV | Δ extinction | Δ s-risk | Δ agency-loss | Δ squandered |');
P('|---|---:|---:|---:|---:|---:|');
const tradeoffs = dataset.actions.map((a) => {
  const after = analyze(dataset, applyAction(base, a), W, ev);
  const t = tailMass(after);
  return {
    a,
    dEv: after.ev - baseA.ev,
    dExt: t.extinction - baseTail.extinction,
    dSrisk: t.srisk - baseTail.srisk,
    dAgency: t.agencyLoss - baseTail.agencyLoss,
    dSquander: t.squandered - baseTail.squandered,
  };
});
for (const t of tradeoffs) {
  P(`| ${t.a.label} | ${sev(t.dEv)} | ${sev(t.dExt)} | ${sev(t.dSrisk)} | ${sev(t.dAgency)} | ${sev(t.dSquander)} |`);
}
P();
P('*A positive number in a risk column means the action, while raising average EV, makes that specific catastrophe **more** likely — the kind of trade a single EV number conceals.*');
P();

// ═══════════════════════════════════════════════════════════════════════════
P('---');
P();
P('## 4. If you bet only on the hopeful worlds — what do they have in common?');
P();
P('Suppose you set the odds aside and ask: *among the scenarios that actually go well, which lever is most over-represented?* Take the best-scoring scenarios (top decile by value under default weights) and, for every factor-state, compare its probability-share **inside** that hopeful set to its baseline share. A high "lift" means "hopeful worlds almost always have this — steer toward it."');
P();
function leverLift(select: (s: Analysis['scenarios'][number]) => boolean) {
  const total = baseA.scenarios.reduce((a, s) => a + s.probability, 0);
  const sel = baseA.scenarios.filter(select);
  const selMass = sel.reduce((a, s) => a + s.probability, 0);
  const rows: { key: string; factor: string; state: string; pIn: number; pBase: number; lift: number }[] = [];
  for (const f of dataset.factors) {
    for (const st of f.states) {
      const inMass = sel.reduce((a, s) => a + (s.scenario[f.id] === st.id ? s.probability : 0), 0);
      const baseMass = baseA.scenarios.reduce((a, s) => a + (s.scenario[f.id] === st.id ? s.probability : 0), 0);
      const pIn = selMass > 0 ? inMass / selMass : 0;
      const pBase = total > 0 ? baseMass / total : 0;
      rows.push({ key: `${f.label} = ${st.label}`, factor: f.id, state: st.id, pIn, pBase, lift: pBase > 0 ? pIn / pBase : 0 });
    }
  }
  return { rows, selMass };
}
const sorted = [...baseA.scenarios].sort((a, b) => b.scalar - a.scalar);
const cutoff = sorted[Math.floor(sorted.length * 0.1)].scalar;
const hopeful = leverLift((s) => s.scalar >= cutoff);
P(`The hopeful decile carries only **${pct(hopeful.selMass)}** of the probability mass (hope is not the median future here). Within it, the biggest lifts:`);
P();
P('| Factor state | share in hopeful worlds | baseline share | lift |');
P('|---|---:|---:|---:|');
hopeful.rows
  .filter((r) => r.lift > 1.05)
  .sort((a, b) => b.lift - a.lift)
  .slice(0, 8)
  .forEach((r) => P(`| ${r.key} | ${pct(r.pIn)} | ${pct(r.pBase)} | ${r.lift.toFixed(2)}× |`));
P();
P('And the mirror image — the factor-states that most distinguish the *worst* decile:');
P();
const doomCut = sorted[Math.floor(sorted.length * 0.9)].scalar;
const doomy = leverLift((s) => s.scalar <= doomCut);
P('| Factor state | share in worst worlds | baseline share | lift |');
P('|---|---:|---:|---:|');
doomy.rows
  .filter((r) => r.lift > 1.05)
  .sort((a, b) => b.lift - a.lift)
  .slice(0, 8)
  .forEach((r) => P(`| ${r.key} | ${pct(r.pIn)} | ${pct(r.pBase)} | ${r.lift.toFixed(2)}× |`));
P();

// ═══════════════════════════════════════════════════════════════════════════
P('---');
P();
P('## 5. Where forecasting pays: value of information vs. leverage');
P();
P('The sensitivity tornado swings each factor across its states. For **objective** factors you can\'t act on it, so a big swing = **value of information** (resolving the question is worth a lot). For **influenceable** ones a big swing = **leverage**. Ranked by swing:');
P();
const sens = sensAll;
P('| Factor | kind | EV swing | best state | worst state |');
P('|---|---|---:|---|---|');
for (const r of sens) {
  const bestLabel = dataset.factors.find((f) => f.id === r.factorId)?.states.find((s) => s.id === r.bestStateId)?.label ?? r.bestStateId;
  const worstLabel = dataset.factors.find((f) => f.id === r.factorId)?.states.find((s) => s.id === r.worstStateId)?.label ?? r.worstStateId;
  P(`| ${r.label} | ${r.kind} | ${r.swing.toFixed(3)} | ${bestLabel} | ${worstLabel} |`);
}
P();
const topObjective = sens.find((r) => r.kind === 'objective');
const topInfluence = sens.find((r) => r.kind === 'influenceable');
if (topObjective) P(`The highest-VoI *objective* question is **${topObjective.label}** (swing ${topObjective.swing.toFixed(3)}) — worth more to *resolve* than most things are to *act on*.`);
if (topInfluence) P(`The highest-leverage *influenceable* factor is **${topInfluence.label}** (swing ${topInfluence.swing.toFixed(3)}).`);
P();

// ═══════════════════════════════════════════════════════════════════════════
P('---');
P();
P('## 6. Diminishing returns & stacking');
P();
P('Does the best action stay best after you\'ve already taken it, or do the levers complement each other? Apply the top action, then re-rank the remaining ones from that new baseline.');
P();
const first = baseRank[0].action;
const afterFirst = applyAction(base, first);
const afterFirstA = analyze(dataset, afterFirst, W, ev);
const secondRank = dataset.actions
  .filter((a) => a.id !== first.id)
  .map((a) => ({ a, gain: analyze(dataset, applyAction(afterFirst, a), W, ev).ev - afterFirstA.ev }))
  .sort((x, y) => y.gain - x.gain);
P(`After **${first.label}** (which alone gains ${sev(baseRank[0].evGain)}), the next-best lever is **${secondRank[0].a.label}** (${sev(secondRank[0].gain)}). Compare its *standalone* gain of ${sev(baseRank.find((r) => r.action.id === secondRank[0].a.id)!.evGain)} — the difference is how much the two levers overlap vs. complement.`);
P();

P('---');
P();
P('## 7. What the marginal tornado hides: conditional leverage');
P();
P('A tornado swings one factor while *averaging over everything else*. For a factor whose effect is conditional, sign-split across value dimensions, and moot in a big chunk of the space, that average is misleading. **Power concentration** is the poster child: marginal swing ≈ 0, but decisive once you look conditionally or per-dimension.');
P();
P('First, the same factor measured on each value dimension alone (swing, baseline beliefs):');
P();
P('| Measured on | Power-concentration swing | its rank among all factors |');
P('|---|---:|---:|');
for (const [name, w] of [
  ['Weighted EV (default)', W],
  ['Survival only', weights({ survival: 1 })],
  ['Agency only', agencyW],
  ['Suffering only', weights({ suffering: 1 })],
] as const) {
  const s = sensitivity(dataset, base, w, ev).sort((a, b) => b.swing - a.swing);
  const rank = s.findIndex((r) => r.factorId === 'powerConcentration') + 1;
  const sw = s.find((r) => r.factorId === 'powerConcentration')?.swing ?? 0;
  P(`| ${name} | ${sw.toFixed(3)} | #${rank} of ${s.length} |`);
}
P();
P('On self-determination it is a top-tier lever; on survival it is nearly irrelevant. A survival-weighted scalar buries it. **If you care about agency, power concentration is one of the most important things on the board — and no current action targets it.**');
P();
P('Second, the concentrated−diffuse gap *conditional* on the world you\'re in (normalized conditional-mean EV; positive = concentrated scores higher):');
P();
P('| Condition | Δ default weights | Δ agency-only |');
P('|---|---:|---:|');
for (const [name, pins] of [
  ['marginal (no condition)', {}],
  ['takeoff = slow', { takeoff: 'slow' }],
  ['coordination = regime', { coordination: 'regime' }],
  ['a survivable world (aligned in time)', { alignmentInTime: 'yes' }],
  ['doom corner', { orthogonality: 'holds', alignmentInTime: 'no', controlDeployed: 'no' }],
  ['aligned & slow & governed', { alignmentInTime: 'yes', takeoff: 'slow', coordination: 'regime' }],
] as const) {
  P(`| ${name} | ${sev(powerGap(pins, W))} | ${sev(powerGap(pins, agencyW))} |`);
}
P();
P('Concentration is near-moot in doom (the takeover moots it) but swings hard in survivable worlds, and on agency it is decisively bad *everywhere the world is live*. Note too the **concentration × coordination interaction** now in the model: a governance regime *checks* concentrated power, so the agency gap shrinks under `coordination = regime` — governance changes what concentration *means*, not just how likely it is.');
P();

P('---');
P();
P('*These are model outputs, not predictions. Their value is in exposing where the model\'s logic is counterintuitive — worth a human double-check on the cells driving each one.*');

// ── write ──────────────────────────────────────────────────────────────────
test('mine findings → docs/FINDINGS.md', () => {
  writeFileSync(OUT, lines.join('\n') + '\n', 'utf8');
  // eslint-disable-next-line no-console
  console.log(`\nWrote ${lines.length} lines to ${OUT}\n`);
});
