/**
 * Research-ROI + action-priority miner → docs/RESEARCH-PRIORITIES.md
 *
 * Two questions, both about *decision* value rather than prediction:
 *
 *  §1  For each OBJECTIVE factor (something we can only research, not act on), what
 *      are the odds that resolving it would change our action priorities? If learning
 *      the answer never changes what we'd do, the research helps us *predict* the
 *      future, not *change* it — near-zero decision-ROI however fascinating.
 *
 *  §2  Rank the ACTIONS by their likelihood of improving EV — not the single-point
 *      gain at baseline beliefs, but how reliably each helps across the whole space
 *      of ways the objective questions could resolve.
 *
 * Wired as a vitest "test" only to borrow the @-aliases (see findings.config.ts):
 *   pnpm exec vitest run --config scripts/findings.config.ts
 *
 * Default probability model (independence × couplings) + cached value surface.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { test } from 'vitest';
import { dataset } from '@model/dataset';
import { analyze, applyAction, cachedEvaluator } from '@engine/index';
import type { Pins } from '@engine/index';
import type { Scenario, ValueVector } from '@model/types';

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), '../docs/RESEARCH-PRIORITIES.md');
const base = dataset.baselineCredences;
const W = dataset.defaultWeights;
const ev = cachedEvaluator;
const EPS = 0.02; // "materially improves" threshold, in EV units

const objectives = dataset.factors.filter((f) => f.kind === 'objective');
const objIds = objectives.map((f) => f.id);

const sev = (x: number) => `${x >= 0 ? '+' : '−'}${Math.abs(x).toFixed(3)}`;
const pct = (x: number) => `${(x * 100).toFixed(0)}%`;
const stateLabel = (fid: string, sid: string) =>
  dataset.factors.find((f) => f.id === fid)?.states.find((s) => s.id === sid)?.label ?? sid;
const actionLabel = (id: string) => dataset.actions.find((a) => a.id === id)?.label ?? id;

/** Normalized conditional-mean EV over the free factors given `pins` (not mass-weighted). */
function condMean(credences: typeof base, pins: Pins): number {
  const a = analyze(dataset, credences, W, ev, pins);
  return a.totalProbability > 0 ? a.ev / a.totalProbability : 0;
}

/** Actions ranked by conditional-mean EV gain given `pins`. */
function rankCond(pins: Pins) {
  const b = condMean(base, pins);
  return dataset.actions
    .map((a) => ({ id: a.id, gain: condMean(applyAction(base, a), pins) - b }))
    .sort((x, y) => y.gain - x.gain);
}

const lines: string[] = [];
const P = (s = '') => lines.push(s);

P('# Research priorities & action ROI');
P();
P('> Auto-generated by [`scripts/research-roi.ts`](../scripts/research-roi.ts).');
P('> Regenerate: `pnpm exec vitest run --config scripts/findings.config.ts`.');
P('>');
P('> Default probability model (independence × couplings) + cached value surface.');
P('> These are properties of the current `dataset.ts`, not claims about the world.');
P();

// ═══════════════════════════════════════════════════════════════════════════
// §1 — research ROI: odds resolving an objective question changes our actions
// ═══════════════════════════════════════════════════════════════════════════
P('## 1. Which objective research would actually change what we do?');
P();
P('Objective factors are things we can only **resolve by research**, not act on. The usual "value of information" is the EV *swing* — but a swing that never changes our chosen action only sharpens a **prediction**; it doesn\'t change the **future**. So the ROI that matters is: *if we resolved this question, what are the odds it flips our action priorities?*');
P();
P('For each objective factor we condition on each possible answer (weighted by its prior), re-rank the actions, and ask whether the **top action** or the **ranked order** changes vs. acting under uncertainty. EVPI is the expected EV we\'d gain by getting to pick our action *after* the answer is known.');
P();

const baseRank = rankCond({});
const baseTopId = baseRank[0].id;
const baseOrder = baseRank.map((r) => r.id).join('>');

type ResearchRow = {
  fid: string;
  label: string;
  pTop: number;
  pOrder: number;
  evpi: number;
  flips: string[];
};
const rows: ResearchRow[] = objectives.map((f) => {
  let pTop = 0;
  let pOrder = 0;
  let withRes = 0;
  let without = 0;
  const flips: string[] = [];
  for (const st of f.states) {
    const p = base[f.id][st.id] ?? 0;
    const pins: Pins = { [f.id]: st.id };
    const r = rankCond(pins);
    const topFlip = r[0].id !== baseTopId;
    const orderChange = r.map((x) => x.id).join('>') !== baseOrder;
    if (topFlip) pTop += p;
    if (orderChange) pOrder += p;
    // EVPI: pick best-per-answer vs commit to the baseline-best action.
    withRes += p * condMean(applyAction(base, dataset.actions.find((a) => a.id === r[0].id)!), pins);
    without += p * condMean(applyAction(base, dataset.actions.find((a) => a.id === baseTopId)!), pins);
    if (orderChange) {
      // Describe the most visible change: the runner-up (or top) that moved.
      flips.push(`${stateLabel(f.id, st.id)} → #1 ${actionLabel(r[0].id)}, #2 ${actionLabel(r[1].id)}`);
    }
  }
  return { fid: f.id, label: f.label, pTop, pOrder, evpi: Math.max(0, withRes - without), flips };
});
rows.sort((a, b) => b.pOrder - a.pOrder || b.evpi - a.evpi);

P('| Objective question | P(changes top action) | P(changes priorities) | EVPI | what a resolution flips |');
P('|---|---:|---:|---:|---|');
for (const r of rows) {
  P(`| ${r.label} | ${pct(r.pTop)} | ${pct(r.pOrder)} | ${sev(r.evpi)} | ${r.flips[0] ?? '— (order unchanged)'} |`);
}
P();
const topFlippers = rows.filter((r) => r.pTop > 0);
const orderOnly = rows.filter((r) => r.pOrder > 0 && r.pTop <= 0);
const inert = rows.filter((r) => r.pOrder <= 0);
P('**Reading it:**');
P();
if (topFlippers.length) {
  P(`- **${topFlippers.map((r) => r.label).join(', ')} can change the very top action** — e.g. ${topFlippers[0].flips[0]}. That is genuine decision-ROI: resolving it changes *what you'd do*, not just what you'd predict. (This became possible only once power concentration got its own lever — before that, no objective resolution moved the #1 action at all.)`);
} else {
  P(`- **No objective resolution changes the #1 action** — the top lever is *${actionLabel(baseTopId)}* however any single objective question resolves; objective research is then almost pure *prediction*.`);
}
P();
if (orderOnly.length) {
  P(`- **${orderOnly.map((r) => r.label).join(', ')} change only the runner-up** (control ↔ coordination): learning that systems deceive, or that offense dominates, demotes *control* — which leans on trustworthy evaluation — beneath *coordination*, which buys time upstream. Worth resolving if you can fund a second priority.`);
}
if (inert.length) {
  P(`- Nothing changes in the action ordering for **${inert.map((r) => r.label).join(', ')}** — however decisive scientifically, these are for forecasting, not for choosing.`);
}
P();
P(`- **EVPI stays small even where the top action flips.** Expected value of perfect information is positive only if the best action differs across a question's answers${topFlippers.length ? ` — which now happens for ${topFlippers[0].label}` : ', which never happens here'}, but the winning action's edge in those worlds is slim, so the *decision value* rounds to ~0. Where the top never flips, EVPI is exactly 0 — pure prediction. Widen or differentiate the action set further and this column grows.`);
P();

// ═══════════════════════════════════════════════════════════════════════════
// §2 — rank actions by likelihood to improve EV across objective uncertainty
// ═══════════════════════════════════════════════════════════════════════════
P('---');
P();
P('## 2. Actions ranked by likelihood to improve EV');
P();
P('Point-estimate EV gain at baseline beliefs is one number; it hides *how reliably* an action helps. Here we roll over the whole distribution of ways the objective questions could resolve (every joint assignment of the 5 objective factors, weighted by its prior under the couplings), and for each action measure the conditional-mean EV gain in each such world.');
P();

// Distribution over objective-factor resolutions, from the coupled joint.
const scenarios = analyze(dataset, base, W, ev).scenarios;
const wKey = (s: Scenario) => objIds.map((id) => s[id]).join('|');
const worldProb: Record<string, number> = {};
const worldPins: Record<string, Pins> = {};
for (const sc of scenarios) {
  const k = wKey(sc.scenario);
  worldProb[k] = (worldProb[k] ?? 0) + sc.probability;
  if (!worldPins[k]) worldPins[k] = Object.fromEntries(objIds.map((id) => [id, sc.scenario[id]])) as Pins;
}
const worlds = Object.keys(worldProb);

type ActionStat = {
  id: string;
  eGain: number;
  pPos: number;
  pMaterial: number;
  pTop: number;
  min: number;
  max: number;
};
const baseByWorld: Record<string, number> = {};
for (const w of worlds) baseByWorld[w] = condMean(base, worldPins[w]);

const stats: ActionStat[] = dataset.actions.map((a) => {
  let eGain = 0;
  let pPos = 0;
  let pMat = 0;
  let min = Infinity;
  let max = -Infinity;
  for (const w of worlds) {
    const g = condMean(applyAction(base, a), worldPins[w]) - baseByWorld[w];
    const p = worldProb[w];
    eGain += p * g;
    if (g > 0) pPos += p;
    if (g > EPS) pMat += p;
    min = Math.min(min, g);
    max = Math.max(max, g);
  }
  return { id: a.id, eGain, pPos, pMaterial: pMat, pTop: 0, min, max };
});
// P(this action is the single best lever) across worlds.
for (const w of worlds) {
  let bestId = dataset.actions[0].id;
  let bestGain = -Infinity;
  for (const a of dataset.actions) {
    const g = condMean(applyAction(base, a), worldPins[w]) - baseByWorld[w];
    if (g > bestGain) {
      bestGain = g;
      bestId = a.id;
    }
  }
  const s = stats.find((x) => x.id === bestId)!;
  s.pTop += worldProb[w];
}
stats.sort((a, b) => b.eGain - a.eGain);

P(`Across **${worlds.length}** objective-world resolutions:`);
P();
P('| Action | E[EV gain] | P(improves) | P(improves ≥ 0.02) | P(is the top lever) | gain range |');
P('|---|---:|---:|---:|---:|---|');
for (const s of stats) {
  P(`| ${actionLabel(s.id)} | ${sev(s.eGain)} | ${pct(s.pPos)} | ${pct(s.pMaterial)} | ${pct(s.pTop)} | ${sev(s.min)} … ${sev(s.max)} |`);
}
P();
P('**Reading it:**');
P();
const top = stats[0];
P(`- **${actionLabel(top.id)}** dominates on every measure: highest expected gain (${sev(top.eGain)}), improves EV in ${pct(top.pPos)} of resolutions, and is the single best lever in ${pct(top.pTop)} of them — large *and* reliable, with no world where it backfires.`);
const backfire = stats.filter((s) => s.pPos < 0.999).sort((a, b) => a.min - b.min);
if (backfire.length) {
  P(`- **Not every lever is a free lunch.** ${backfire.map((s) => `${actionLabel(s.id)} (worst case ${sev(s.min)}, helps in ${pct(s.pPos)})`).join(' and ')} can actually *lower* EV in a minority of worlds. That's the deception logic biting: deploying a leash (control) on a system that fools its evaluations, or accelerating defenses that mostly harden a controlled-but-deceptive world, can leave you slightly worse than not leaning on them. Alignment-funding and coordination help in 100% of worlds.`);
  P(`- So "likelihood to improve EV" reorders the middle by **risk appetite**: coordination has the *lower ceiling* but never backfires (a safe, reliable second bet), while control has the *higher ceiling* (best case ${sev(stats.find((s) => s.id === 'standardizeControl')?.max ?? 0)}) but an ~8% chance of costing you. Which you prefer as #2 is exactly the runner-up flip from §1.`);
}
P(`- The mean-gain ordering still matches the baseline single-point ranking, so the *headline* priority is **robust to objective uncertainty** — you don't need to resolve the science to know alignment-funding leads. (The flip side of §1: the levers are insensitive to the objective questions.)`);
P();
P('---');
P();
P('*Model outputs, not predictions. The recurring signal across both sections: the action set is too coarse and too correlated for objective knowledge to change the plan — the highest-leverage meta-move is designing more differentiated actions.*');

test('research ROI → docs/RESEARCH-PRIORITIES.md', () => {
  writeFileSync(OUT, lines.join('\n') + '\n', 'utf8');
  // eslint-disable-next-line no-console
  console.log(`\nWrote ${lines.length} lines to ${OUT}\n`);
});
